# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module Cl_a1fia_aar_create_qaf_eco::If_a1fia_aar_create_qaf_eco


   module_function
   if_a1fia_aar_create_qaf_eco=If_a1fia_aar_create_qaf_eco

end
