
C_EOF_Sym = EOF_Sym = 	0	#  EOF */
C_CRLF_Sym = 0.5

C_identifierSym = 1 # identifier 
C_numberSym = 2 # number 
C_hexnumberSym = 3 # hexnumber 
C_stringD1Sym = 4 # string1 
C_charSym = 5 # char 
C_ColonSym = 6 # Colon 
C_spaceD1Sym = 7 # space1 
C_REPORTSym = 8 # "REPORT" 
C_NOSym = 9 # "NO" 
C_STANDARDSym = 10 # "STANDARD" 
C_PAGESym = 11 # "PAGE" 
C_HEADINGSym = 12 # "HEADING" 
C_LINEMinusSIZESym = 13 # "LINE-SIZE" 
C_LINEMinusCOUNTSym = 14 # "LINE-COUNT" 
C_LparenSym = 15 # "(" 
C_RparenSym = 16 # ")" 
C_MESSAGEMinusIDSym = 17 # "MESSAGE-ID" 
C_DEFININGSym = 18 # "DEFINING" 
C_DATABASESym = 19 # "DATABASE" 
C_REDUCEDSym = 20 # "REDUCED" 
C_FUNCTIONALITYSym = 21 # "FUNCTIONALITY" 
C_PointSym = 22 # "." 
C_FUNCTIONSym = 23 # "FUNCTION" 
C_SELECTSym = 24 # "SELECT" 
C_MessageSym = 25 # "Message" 
C_WITHSym = 26 # "WITH" 
C_TABLESSym = 27 # "TABLES" 
C_MOVESym = 28 # "MOVE" 
C_APPENDSym = 29 # "APPEND" 
C_CONCATENATESym = 30 # "CONCATENATE" 
C_SEARCHSym = 31 # "SEARCH" 
C_RAISESym = 32 # "RAISE" 
C_DATASym = 33 # "DATA" 
C_CONSTANTSSym = 34 # "CONSTANTS" 
C_WRITESym = 35 # "WRITE" 
C_LOOPSym = 36 # "LOOP" 
C_CONTINUESym = 37 # "CONTINUE" 
C_CASESym = 38 # "CASE" 
C_AUTHORITYMinusCHECKSym = 39 # "AUTHORITY-CHECK" 
C_DELETESym = 40 # "DELETE" 
C_DOSym = 41 # "DO" 
C_EVENTSSym = 42 # "EVENTS" 
C_ONSym = 43 # "ON" 
C_OPENSym = 44 # "OPEN" 
C_FETCHSym = 45 # "FETCH" 
C_PROVIDESym = 46 # "PROVIDE" 
C_READSym = 47 # "READ" 
C_SORTSym = 48 # "SORT" 
C_SUBMITSym = 49 # "SUBMIT" 
C_TRYSym = 50 # "TRY" 
C_TYPESSym = 51 # "TYPES" 
C_forSym = 52 # "for" 
C_UPDATESym = 53 # "UPDATE" 
C_WHILESym = 54 # "WHILE" 
C_IFSym = 55 # "IF" 
C_CLASSSym = 56 # "CLASS" 
C_METHODSym = 57 # "METHOD" 
C_METHODSSym = 58 # "METHODS" 
C_ADDSym = 59 # "ADD" 
C_ADDMinusCORRESPONDINGSym = 60 # "ADD-CORRESPONDING" 
C_ALIASESSym = 61 # "ALIASES" 
C_ASSERTSym = 62 # "ASSERT" 
C_ASSIGNSym = 63 # "ASSIGN" 
C_BACKSym = 64 # "BACK" 
C_BREAKMinusPOINTSym = 65 # "BREAK-POINT" 
C_CALLSym = 66 # "CALL" 
C_CATCHSym = 67 # "CATCH" 
C_CHECKSym = 68 # "CHECK" 
C_CLASSMinusDATASym = 69 # "CLASS-DATA" 
C_CLASSMinusEVENTSSym = 70 # "CLASS-EVENTS" 
C_CLASSMinusPOOLSym = 71 # "CLASS-POOL" 
C_CLEARSym = 72 # "CLEAR" 
C_CLOSESym = 73 # "CLOSE" 
C_COLLECTSym = 74 # "COLLECT" 
C_COMMITSym = 75 # "COMMIT" 
C_COMPUTESym = 76 # "COMPUTE" 
C_CONDENSESym = 77 # "CONDENSE" 
C_CONTROLSSym = 78 # "CONTROLS" 
C_CONVERTSym = 79 # "CONVERT" 
C_CREATESym = 80 # "CREATE" 
C_DEMANDSym = 81 # "DEMAND" 
C_DESCRIBESym = 82 # "DESCRIBE" 
C_DETAILSym = 83 # "DETAIL" 
C_DIVIDESym = 84 # "DIVIDE" 
C_DIVIDEMinusCORRESPONDINGSym = 85 # "DIVIDE-CORRESPONDING" 
C_EDITORMinusCALLSym = 86 # "EDITOR-CALL" 
C_ENDMinusOFMinusPAGESym = 87 # "END-OF-PAGE" 
C_ENDMinusOFMinusSELECTIONSym = 88 # "END-OF-SELECTION" 
C_EXITSym = 89 # "EXIT" 
C_EXPORTSym = 90 # "EXPORT" 
C_EXTRACTSym = 91 # "EXTRACT" 
C_FIELDMinusGROUPSSym = 92 # "FIELD-GROUPS" 
C_FIELDMinusSYMBOLSSym = 93 # "FIELD-SYMBOLS" 
C_FIELDSSym = 94 # "FIELDS" 
C_FINDSym = 95 # "FIND" 
C_FORMATSym = 96 # "FORMAT" 
C_FREESym = 97 # "FREE" 
C_FUNCTIONMinusPOOLSym = 98 # "FUNCTION-POOL" 
C_GENERATESym = 99 # "GENERATE" 
C_GETSym = 100 # "GET" 
C_HIDESym = 101 # "HIDE" 
C_IMPORTSym = 102 # "IMPORT" 
C_INCLUDESym = 103 # "INCLUDE" 
C_INFOTYPESSym = 104 # "INFOTYPES" 
C_INITIALIZATIONSym = 105 # "INITIALIZATION" 
C_INPUTSym = 106 # "INPUT" 
C_INSERTSym = 107 # "INSERT" 
C_INTERFACESym = 108 # "INTERFACE" 
C_INTERFACEMinusPOOLSym = 109 # "INTERFACE-POOL" 
C_INTERFACESSym = 110 # "INTERFACES" 
C_LEAVESym = 111 # "LEAVE" 
C_LOADMinusOFMinusPROGRAMSym = 112 # "LOAD-OF-PROGRAM" 
C_LOCALSym = 113 # "LOCAL" 
C_LOGMinusPOINTSym = 114 # "LOG-POINT" 
C_MAXIMUMSym = 115 # "MAXIMUM" 
C_MINIMUMSym = 116 # "MINIMUM" 
C_MODULESym = 117 # "MODULE" 
C_MULTIPLYSym = 118 # "MULTIPLY" 
C_MULTIPLYMinusCORRESPONDINGSym = 119 # "MULTIPLY-CORRESPONDING" 
C_NEWMinusLINESym = 120 # "NEW-LINE" 
C_NEWMinusPAGESym = 121 # "NEW-PAGE" 
C_NEWMinusSECTIONSym = 122 # "NEW-SECTION" 
C_NODESSym = 123 # "NODES" 
C_OVERLAYSym = 124 # "OVERLAY" 
C_PACKSym = 125 # "PACK" 
C_PARAMETERSSym = 126 # "PARAMETERS" 
C_PERFORMSym = 127 # "PERFORM" 
C_POSITIONSym = 128 # "POSITION" 
C_PRINTMinusCONTROLSym = 129 # "PRINT-CONTROL" 
C_PROGRAMSym = 130 # "PROGRAM" 
C_RANGESSym = 131 # "RANGES" 
C_RECEIVESym = 132 # "RECEIVE" 
C_REFRESHSym = 133 # "REFRESH" 
C_REJECTSym = 134 # "REJECT" 
C_REPLACESym = 135 # "REPLACE" 
C_RESERVESym = 136 # "RESERVE" 
C_RESUMESym = 137 # "RESUME" 
C_RETRYSym = 138 # "RETRY" 
C_RETURNSym = 139 # "RETURN" 
C_ROLLBACKSym = 140 # "ROLLBACK" 
C_SCROLLSym = 141 # "SCROLL" 
C_SELECTMinusOPTIONSSym = 142 # "SELECT-OPTIONS" 
C_SELECTIONMinusSCREENSym = 143 # "SELECTION-SCREEN" 
C_SETSym = 144 # "SET" 
C_SHIFTSym = 145 # "SHIFT" 
C_SKIPSym = 146 # "SKIP" 
C_STOPSym = 147 # "STOP" 
C_SUBTRACTSym = 148 # "SUBTRACT" 
C_SUBTRACTMinusCORRESPONDINGSym = 149 # "SUBTRACT-CORRESPONDING" 
C_SUMSym = 150 # "SUM" 
C_SUMMARYSym = 151 # "SUMMARY" 
C_SUMMINGSym = 152 # "SUMMING" 
C_SUPPLYSym = 153 # "SUPPLY" 
C_SUPPRESSSym = 154 # "SUPPRESS" 
C_SYNTAXMinusCHECKSym = 155 # "SYNTAX-CHECK" 
C_TESTMinusINJECTIONSym = 156 # "TEST-INJECTION" 
C_TESTMinusSEAMSym = 157 # "TEST-SEAM" 
C_TOPMinusOFMinusPAGESym = 158 # "TOP-OF-PAGE" 
C_TRANSFERSym = 159 # "TRANSFER" 
C_TRANSLATESym = 160 # "TRANSLATE" 
C_TRUNCATESym = 161 # "TRUNCATE" 
C_TYPEMinusPOOLSym = 162 # "TYPE-POOL" 
C_TYPEMinusPOOLSSym = 163 # "TYPE-POOLS" 
C_ULINESym = 164 # "ULINE" 
C_UNASSIGNSym = 165 # "UNASSIGN" 
C_UNPACKSym = 166 # "UNPACK" 
C_WAITSym = 167 # "WAIT" 
C_WINDOWSym = 168 # "WINDOW" 
C_SPLITSym = 169 # "SPLIT" 
C_BarBarSym = 170 # "||" 
C_ORSym = 171 # "OR" 
C_EQUIVSym = 172 # "EQUIV" 
C_AndAndSym = 173 # "&&" 
C_ANDSym = 174 # "AND" 
C_BarSym = 175 # "|" 
C_UparrowSym = 176 # "^" 
C_AndSym = 177 # "&" 
C_EqualSym = 178 # "=" 
C_EQSym = 179 # "EQ" 
C_LessGreaterSym = 180 # "<>" 
C_NESym = 181 # "NE" 
C_ISSym = 182 # "IS" 
C_NOTSym = 183 # "NOT" 
C_BETWEENSym = 184 # "BETWEEN" 
C_LessSym = 185 # "<" 
C_LTSym = 186 # "LT" 
C_GreaterSym = 187 # ">" 
C_GTSym = 188 # "GT" 
C_LessEqualSym = 189 # "<=" 
C_LESym = 190 # "LE" 
C_GreaterEqualSym = 191 # ">=" 
C_GESym = 192 # "GE" 
C_COSym = 193 # "CO" 
C_CNSym = 194 # "CN" 
C_CASym = 195 # "CA" 
C_NASym = 196 # "NA" 
C_CSSym = 197 # "CS" 
C_NSSym = 198 # "NS" 
C_CPSym = 199 # "CP" 
C_NPSym = 200 # "NP" 
C_BYTEMinusCOSym = 201 # "BYTE-CO" 
C_BYTEMinusCNSym = 202 # "BYTE-CN" 
C_BYTEMinusCASym = 203 # "BYTE-CA" 
C_BYTEMinusNASym = 204 # "BYTE-NA" 
C_BYTEMinusCSSym = 205 # "BYTE-CS" 
C_BYTEMinusNSSym = 206 # "BYTE-NS" 
C_LessLessSym = 207 # "<<" 
C_GreaterGreaterSym = 208 # ">>" 
C_PlusSym = 209 # "+" 
C_MinusSym = 210 # "-" 
C_StarSym = 211 # "*" 
C_SlashSym = 212 # "/" 
C_DIVSym = 213 # "DIV" 
C_PercentSym = 214 # "%" 
C_MODSym = 215 # "MOD" 
C_StarStarSym = 216 # "**" 
C_PlusPlusSym = 217 # "++" 
C_MinusMinusSym = 218 # "--" 
C_LbrackSym = 219 # "[" 
C_RbrackSym = 220 # "]" 
C_MinusGreaterSym = 221 # "->" 
C_EqualGreaterSym = 222 # "=>" 
C_CommaSym = 223 # "," 
C_StarEqualSym = 224 # "*=" 
C_SlashEqualSym = 225 # "/=" 
C_PercentEqualSym = 226 # "%=" 
C_PlusEqualSym = 227 # "+=" 
C_MinusEqualSym = 228 # "-=" 
C_AndEqualSym = 229 # "&=" 
C_UparrowEqualSym = 230 # "^=" 
C_BarEqualSym = 231 # "|=" 
C_LessLessEqualSym = 232 # "<<=" 
C_GreaterGreaterEqualSym = 233 # ">>=" 
C_BangSym = 234 # "!" 
C_TildeSym = 235 # "~" 
C_INSTANCESym = 236 # "INSTANCE" 
C_OFSym = 237 # "OF" 
C_INSym = 238 # "IN" 
C_INITIALSym = 239 # "INITIAL" 
C_BOUNDSym = 240 # "BOUND" 
C_ASSIGNEDSym = 241 # "ASSIGNED" 
C_SUPPLIEDSym = 242 # "SUPPLIED" 
C_REQUESTEDSym = 243 # "REQUESTED" 
No_Sym = 244 # not 
C_PreProcessorSym = 245 # PreProcessor 


MAXT =	No_Sym 	# Max Terminals */
C_MAXT = MAXT


SYMS=[  
    "EOF",
    "identifier",
"number",
"hexnumber",
"string1",
"char",
"Colon",
"space1",
"REPORT",
"NO",
"STANDARD",
"PAGE",
"HEADING",
"LINE-SIZE",
"LINE-COUNT",
"(",
")",
"MESSAGE-ID",
"DEFINING",
"DATABASE",
"REDUCED",
"FUNCTIONALITY",
".",
"FUNCTION",
"SELECT",
"Message",
"WITH",
"TABLES",
"MOVE",
"APPEND",
"CONCATENATE",
"SEARCH",
"RAISE",
"DATA",
"CONSTANTS",
"WRITE",
"LOOP",
"CONTINUE",
"CASE",
"AUTHORITY-CHECK",
"DELETE",
"DO",
"EVENTS",
"ON",
"OPEN",
"FETCH",
"PROVIDE",
"READ",
"SORT",
"SUBMIT",
"TRY",
"TYPES",
"for",
"UPDATE",
"WHILE",
"IF",
"CLASS",
"METHOD",
"METHODS",
"ADD",
"ADD-CORRESPONDING",
"ALIASES",
"ASSERT",
"ASSIGN",
"BACK",
"BREAK-POINT",
"CALL",
"CATCH",
"CHECK",
"CLASS-DATA",
"CLASS-EVENTS",
"CLASS-POOL",
"CLEAR",
"CLOSE",
"COLLECT",
"COMMIT",
"COMPUTE",
"CONDENSE",
"CONTROLS",
"CONVERT",
"CREATE",
"DEMAND",
"DESCRIBE",
"DETAIL",
"DIVIDE",
"DIVIDE-CORRESPONDING",
"EDITOR-CALL",
"END-OF-PAGE",
"END-OF-SELECTION",
"EXIT",
"EXPORT",
"EXTRACT",
"FIELD-GROUPS",
"FIELD-SYMBOLS",
"FIELDS",
"FIND",
"FORMAT",
"FREE",
"FUNCTION-POOL",
"GENERATE",
"GET",
"HIDE",
"IMPORT",
"INCLUDE",
"INFOTYPES",
"INITIALIZATION",
"INPUT",
"INSERT",
"INTERFACE",
"INTERFACE-POOL",
"INTERFACES",
"LEAVE",
"LOAD-OF-PROGRAM",
"LOCAL",
"LOG-POINT",
"MAXIMUM",
"MINIMUM",
"MODULE",
"MULTIPLY",
"MULTIPLY-CORRESPONDING",
"NEW-LINE",
"NEW-PAGE",
"NEW-SECTION",
"NODES",
"OVERLAY",
"PACK",
"PARAMETERS",
"PERFORM",
"POSITION",
"PRINT-CONTROL",
"PROGRAM",
"RANGES",
"RECEIVE",
"REFRESH",
"REJECT",
"REPLACE",
"RESERVE",
"RESUME",
"RETRY",
"RETURN",
"ROLLBACK",
"SCROLL",
"SELECT-OPTIONS",
"SELECTION-SCREEN",
"SET",
"SHIFT",
"SKIP",
"STOP",
"SUBTRACT",
"SUBTRACT-CORRESPONDING",
"SUM",
"SUMMARY",
"SUMMING",
"SUPPLY",
"SUPPRESS",
"SYNTAX-CHECK",
"TEST-INJECTION",
"TEST-SEAM",
"TOP-OF-PAGE",
"TRANSFER",
"TRANSLATE",
"TRUNCATE",
"TYPE-POOL",
"TYPE-POOLS",
"ULINE",
"UNASSIGN",
"UNPACK",
"WAIT",
"WINDOW",
"SPLIT",
"||",
"OR",
"EQUIV",
"&&",
"AND",
"|",
"^",
"&",
"=",
"EQ",
"<>",
"NE",
"IS",
"NOT",
"BETWEEN",
"<",
"LT",
">",
"GT",
"<=",
"LE",
">=",
"GE",
"CO",
"CN",
"CA",
"NA",
"CS",
"NS",
"CP",
"NP",
"BYTE-CO",
"BYTE-CN",
"BYTE-CA",
"BYTE-NA",
"BYTE-CS",
"BYTE-NS",
"<<",
">>",
"+",
"-",
"*",
"/",
"DIV",
"%",
"MOD",
"**",
"++",
"--",
"[",
"]",
"->",
"=>",
",",
"*=",
"/=",
"%=",
"+=",
"-=",
"&=",
"^=",
"|=",
"<<=",
">>=",
"!",
"~",
"INSTANCE",
"OF",
"IN",
"INITIAL",
"BOUND",
"ASSIGNED",
"SUPPLIED",
"REQUESTED",
"not",
"PreProcessor",

]
