
C_EOF_Sym = EOF_Sym = 	0	#  EOF */
C_CRLF_Sym = 0.5

C_identifierSym = 1 # identifier 
C_numberSym = 2 # number 
C_hexnumberSym = 3 # hexnumber 
C_stringD1Sym = 4 # string1 
C_charSym = 5 # char 
C_ColonSym = 6 # Colon 
C_spaceD1Sym = 7 # space1 
C_LparenSym = 8 # "(" 
C_RparenSym = 9 # ")" 
C_REPORTSym = 10 # "REPORT" 
C_NOSym = 11 # "NO" 
C_STANDARDSym = 12 # "STANDARD" 
C_PAGESym = 13 # "PAGE" 
C_HEADINGSym = 14 # "HEADING" 
C_LINEMinusSIZESym = 15 # "LINE-SIZE" 
C_LINEMinusCOUNTSym = 16 # "LINE-COUNT" 
C_MESSAGEMinusIDSym = 17 # "MESSAGE-ID" 
C_DEFININGSym = 18 # "DEFINING" 
C_DATABASESym = 19 # "DATABASE" 
C_REDUCEDSym = 20 # "REDUCED" 
C_FUNCTIONALITYSym = 21 # "FUNCTIONALITY" 
C_PointSym = 22 # "." 
C_FUNCTIONSym = 23 # "FUNCTION" 
C_ENDFUNCTIONSym = 24 # "ENDFUNCTION" 
C_ENDSELECTSym = 25 # "ENDSELECT" 
C_FIELDSSym = 26 # "FIELDS" 
C_DISTINCTSym = 27 # "DISTINCT" 
C_StarSym = 28 # "*" 
C_CommaSym = 29 # "," 
C_FROMSym = 30 # "FROM" 
C_ASSym = 31 # "AS" 
C_USINGSym = 32 # "USING" 
C_CLIENTSym = 33 # "CLIENT" 
C_SPECIFIEDSym = 34 # "SPECIFIED" 
C_TildeSym = 35 # "~" 
C_TildeStarSym = 36 # "~*" 
C_aggregateSym = 37 # "aggregate" 
C_INNERSym = 38 # "INNER" 
C_LEFTSym = 39 # "LEFT" 
C_RIGHTSym = 40 # "RIGHT" 
C_OUTERSym = 41 # "OUTER" 
C_CROSSSym = 42 # "CROSS" 
C_JOINSym = 43 # "JOIN" 
C_ONSym = 44 # "ON" 
C_ORDERSym = 45 # "ORDER" 
C_BYSym = 46 # "BY" 
C_PRIMARYSym = 47 # "PRIMARY" 
C_KEYSym = 48 # "KEY" 
C_ASCENDINGSym = 49 # "ASCENDING" 
C_DESCENDINGSym = 50 # "DESCENDING" 
C_INTOSym = 51 # "INTO" 
C_APPENDINGSym = 52 # "APPENDING" 
C_CORRESPONDINGSym = 53 # "CORRESPONDING" 
C_OFSym = 54 # "OF" 
C_TABLESym = 55 # "TABLE" 
C_PACKAGESym = 56 # "PACKAGE" 
C_SIZESym = 57 # "SIZE" 
C_AtDATASym = 58 # "@DATA" 
C_SELECTSym = 59 # "SELECT" 
C_SINGLESym = 60 # "SINGLE" 
C_FORSym = 61 # "FOR" 
C_UPDATESym = 62 # "UPDATE" 
C_ALLSym = 63 # "ALL" 
C_ENTRIESSym = 64 # "ENTRIES" 
C_INSym = 65 # "IN" 
C_WHERESym = 66 # "WHERE" 
C_GROUPSym = 67 # "GROUP" 
C_HAVINGSym = 68 # "HAVING" 
C_UNIONSym = 69 # "UNION" 
C_EXTENDEDSym = 70 # "EXTENDED" 
C_RESULTSym = 71 # "RESULT" 
C_AtSym = 72 # "@" 
C_CREATINGSym = 73 # "CREATING" 
C_READERSym = 74 # "READER" 
C_LOCATORSym = 75 # "LOCATOR" 
C_COLUMNSSym = 76 # "COLUMNS" 
C_OTHERSym = 77 # "OTHER" 
C_BLOBSym = 78 # "BLOB" 
C_CLOBSym = 79 # "CLOB" 
C_OFFSETSym = 80 # "OFFSET" 
C_UPSym = 81 # "UP" 
C_TOSym = 82 # "TO" 
C_ROWSSym = 83 # "ROWS" 
C_BYPASSINGSym = 84 # "BYPASSING" 
C_BUFFERSym = 85 # "BUFFER" 
C_CONNECTIONSym = 86 # "CONNECTION" 
C_PlusSym = 87 # "+" 
C_WITHSym = 88 # "WITH" 
C_ENDWITHSym = 89 # "ENDWITH" 
C_TABLESSym = 90 # "TABLES" 
C_MOVESym = 91 # "MOVE" 
C_EXACTSym = 92 # "EXACT" 
C_QueryTOSym = 93 # "?TO" 
C_PERCENTAGESym = 94 # "PERCENTAGE" 
C_MOVEMinusCORRESPONDINGSym = 95 # "MOVE-CORRESPONDING" 
C_EXPANDINGSym = 96 # "EXPANDING" 
C_NESTEDSym = 97 # "NESTED" 
C_KEEPINGSym = 98 # "KEEPING" 
C_TARGETSym = 99 # "TARGET" 
C_APPENDSym = 100 # "APPEND" 
C_INITIALSym = 101 # "INITIAL" 
C_LINESym = 102 # "LINE" 
C_LbrackSym = 103 # "[" 
C_RbrackSym = 104 # "]" 
C_SORTEDSym = 105 # "SORTED" 
C_ASSIGNINGSym = 106 # "ASSIGNING" 
C_CASTINGSym = 107 # "CASTING" 
C_REFERENCESym = 108 # "REFERENCE" 
C_CONCATENATESym = 109 # "CONCATENATE" 
C_CHARACTERSym = 110 # "CHARACTER" 
C_BYTESym = 111 # "BYTE" 
C_MODESym = 112 # "MODE" 
C_SEPARATEDSym = 113 # "SEPARATED" 
C_RESPECTINGSym = 114 # "RESPECTING" 
C_BLANKSSym = 115 # "BLANKS" 
C_SEARCHSym = 116 # "SEARCH" 
C_STARTINGSym = 117 # "STARTING" 
C_ATSym = 118 # "AT" 
C_ENDINGSym = 119 # "ENDING" 
C_ABBREVIATEDSym = 120 # "ABBREVIATED" 
C_ANDSym = 121 # "AND" 
C_MARKSym = 122 # "MARK" 
C_RAISESym = 123 # "RAISE" 
C_EVENTSym = 124 # "EVENT" 
C_EXPORTINGSym = 125 # "EXPORTING" 
C_RESUMABLESym = 126 # "RESUMABLE" 
C_EXCEPTIONSym = 127 # "EXCEPTION" 
C_TYPESym = 128 # "TYPE" 
C_MESSAGESym = 129 # "MESSAGE" 
C_IDSym = 130 # "ID" 
C_NUMBERSym = 131 # "NUMBER" 
C_DISPLAYSym = 132 # "DISPLAY" 
C_LIKESym = 133 # "LIKE" 
C_RAISINGSym = 134 # "RAISING" 
C_EqualSym = 135 # "=" 
C_INDEXSym = 136 # "INDEX" 
C_TEXTSym = 137 # "TEXT" 
C_WITHOUTSym = 138 # "WITHOUT" 
C_MEMBERSSym = 139 # "MEMBERS" 
C_LOOPSym = 140 # "LOOP" 
C_TRANSPORTINGSym = 141 # "TRANSPORTING" 
C_VERSIONSym = 142 # "VERSION" 
C_SCREENSym = 143 # "SCREEN" 
C_ENDLOOPSym = 144 # "ENDLOOP" 
C_DECIMALSSym = 145 # "DECIMALS" 
C_LOBSym = 146 # "LOB" 
C_HANDLESym = 147 # "HANDLE" 
C_BOXEDSym = 148 # "BOXED" 
C_REFSym = 149 # "REF" 
C_EMPTYSym = 150 # "EMPTY" 
C_HEADERSym = 151 # "HEADER" 
C_UNIQUESym = 152 # "UNIQUE" 
C_NONMinusUNIQUESym = 153 # "NON-UNIQUE" 
C_primaryUnderscorekeySym = 154 # "primary_key" 
C_ALIASSym = 155 # "ALIAS" 
C_COMPONENTSSym = 156 # "COMPONENTS" 
C_DEFAULTSym = 157 # "DEFAULT" 
C_HASHEDSym = 158 # "HASHED" 
C_RANGESym = 159 # "RANGE" 
C_DATASym = 160 # "DATA" 
C_STATICSSym = 161 # "STATICS" 
C_BEGINSym = 162 # "BEGIN" 
C_COMMONSym = 163 # "COMMON" 
C_PARTSym = 164 # "PART" 
C_READMinusONLYSym = 165 # "READ-ONLY" 
C_OCCURSSym = 166 # "OCCURS" 
C_ENDSym = 167 # "END" 
C_VALIDSym = 168 # "VALID" 
C_BETWEENSym = 169 # "BETWEEN" 
C_VALUESym = 170 # "VALUE" 
C_ISSym = 171 # "IS" 
C_CONSTANTSSym = 172 # "CONSTANTS" 
C_WRITESym = 173 # "WRITE" 
C_SlashSym = 174 # "/" 
C_StarStarSym = 175 # "**" 
C_UNDERSym = 176 # "UNDER" 
C_NOMinusGAPSym = 177 # "NO-GAP" 
C_LEFTMinusJUSTIFIEDSym = 178 # "LEFT-JUSTIFIED" 
C_CENTEREDSym = 179 # "CENTERED" 
C_RIGHTMinusJUSTIFIEDSym = 180 # "RIGHT-JUSTIFIED" 
C_EXPONENTSym = 181 # "EXPONENT" 
C_NOMinusGROUPINGSym = 182 # "NO-GROUPING" 
C_NOMinusSIGNSym = 183 # "NO-SIGN" 
C_NOMinusZEROSym = 184 # "NO-ZERO" 
C_CURRENCYSym = 185 # "CURRENCY" 
C_ROUNDSym = 186 # "ROUND" 
C_UNITSym = 187 # "UNIT" 
C_ENVIRONMENTSym = 188 # "ENVIRONMENT" 
C_TIMESym = 189 # "TIME" 
C_FORMATSym = 190 # "FORMAT" 
C_ZONESym = 191 # "ZONE" 
C_STYLESym = 192 # "STYLE" 
C_EDITSym = 193 # "EDIT" 
C_MASKSym = 194 # "MASK" 
C_DDSlashMMSlashYYSym = 195 # "DD/MM/YY" 
C_MMSlashDDSlashYYSym = 196 # "MM/DD/YY" 
C_DDSlashMMSlashYYYYSym = 197 # "DD/MM/YYYY" 
C_MMSlashDDSlashYYYYSym = 198 # "MM/DD/YYYY" 
C_DDMMYYSym = 199 # "DDMMYY" 
C_MMDDYYSym = 200 # "MMDDYY" 
C_YYMMDDSym = 201 # "YYMMDD" 
C_CHECKBOXSym = 202 # "CHECKBOX" 
C_ICONSym = 203 # "ICON" 
C_SYMBOLSym = 204 # "SYMBOL" 
C_QUICKINFOSym = 205 # "QUICKINFO" 
C_CONTINUESym = 206 # "CONTINUE" 
C_CASESym = 207 # "CASE" 
C_WHENSym = 208 # "WHEN" 
C_ORSym = 209 # "OR" 
C_OTHERSSym = 210 # "OTHERS" 
C_ENDCASESym = 211 # "ENDCASE" 
C_FIELDSym = 212 # "FIELD" 
C_DUMMYSym = 213 # "DUMMY" 
C_AUTHORITYMinusCHECKSym = 214 # "AUTHORITY-CHECK" 
C_OBJECTSym = 215 # "OBJECT" 
C_USERSym = 216 # "USER" 
C_DELETESym = 217 # "DELETE" 
C_DATASETSym = 218 # "DATASET" 
C_ADJACENTSym = 219 # "ADJACENT" 
C_DUPLICATESSym = 220 # "DUPLICATES" 
C_COMPARINGSym = 221 # "COMPARING" 
C_MEMORYSym = 222 # "MEMORY" 
C_SHAREDSym = 223 # "SHARED" 
C_VARYINGSym = 224 # "VARYING" 
C_NEXTSym = 225 # "NEXT" 
C_DOSym = 226 # "DO" 
C_TIMESSym = 227 # "TIMES" 
C_ENDDOSym = 228 # "ENDDO" 
C_OPTIONALSym = 229 # "OPTIONAL" 
C_EVENTSSym = 230 # "EVENTS" 
C_MODIFYSym = 231 # "MODIFY" 
C_CURRENTSym = 232 # "CURRENT" 
C_CHANGESym = 233 # "CHANGE" 
C_ENDONSym = 234 # "ENDON" 
C_OPENSym = 235 # "OPEN" 
C_CURSORSym = 236 # "CURSOR" 
C_HOLDSym = 237 # "HOLD" 
C_INPUTSym = 238 # "INPUT" 
C_OUTPUTSym = 239 # "OUTPUT" 
C_BINARYSym = 240 # "BINARY" 
C_ENCODINGSym = 241 # "ENCODING" 
C_SKIPPINGSym = 242 # "SKIPPING" 
C_BYTEMinusORDERSym = 243 # "BYTE-ORDER" 
C_NONMinusUNICODESym = 244 # "NON-UNICODE" 
C_NATIVESym = 245 # "NATIVE" 
C_SMARTSym = 246 # "SMART" 
C_UNIXSym = 247 # "UNIX" 
C_WINDOWSSym = 248 # "WINDOWS" 
C_LINEFEEDSym = 249 # "LINEFEED" 
C_LEGACYSym = 250 # "LEGACY" 
C_BIGSym = 251 # "BIG" 
C_LITTLESym = 252 # "LITTLE" 
C_ENDIANSym = 253 # "ENDIAN" 
C_CODESym = 254 # "CODE" 
C_POSITIONSym = 255 # "POSITION" 
C_FILTERSym = 256 # "FILTER" 
C_IGNORINGSym = 257 # "IGNORING" 
C_CONVERSIONSym = 258 # "CONVERSION" 
C_ERRORSSym = 259 # "ERRORS" 
C_REPLACEMENTSym = 260 # "REPLACEMENT" 
C_FETCHSym = 261 # "FETCH" 
C_BOUNDSSym = 262 # "BOUNDS" 
C_PROVIDESym = 263 # "PROVIDE" 
C_INCLUDINGSym = 264 # "INCLUDING" 
C_GAPSSym = 265 # "GAPS" 
C_ENDPROVIDESym = 266 # "ENDPROVIDE" 
C_READSym = 267 # "READ" 
C_MAXIMUMSym = 268 # "MAXIMUM" 
C_ACTUALSym = 269 # "ACTUAL" 
C_WIDTHSym = 270 # "WIDTH" 
C_TEXTPOOLSym = 271 # "TEXTPOOL" 
C_LANGUAGESym = 272 # "LANGUAGE" 
C_SORTSym = 273 # "SORT" 
C_SUBMITSym = 274 # "SUBMIT" 
C_SELECTIONMinusSCREENSym = 275 # "SELECTION-SCREEN" 
C_VIASym = 276 # "VIA" 
C_SELECTIONMinusSETSym = 277 # "SELECTION-SET" 
C_SELECTIONMinusSETSSym = 278 # "SELECTION-SETS" 
C_PROGRAMSym = 279 # "PROGRAM" 
C_SELECTIONMinusTABLESym = 280 # "SELECTION-TABLE" 
C_EQSym = 281 # "EQ" 
C_NESym = 282 # "NE" 
C_CPSym = 283 # "CP" 
C_NPSym = 284 # "NP" 
C_GESym = 285 # "GE" 
C_LTSym = 286 # "LT" 
C_LESym = 287 # "LE" 
C_GTSym = 288 # "GT" 
C_NOTSym = 289 # "NOT" 
C_FREESym = 290 # "FREE" 
C_SELECTIONSSym = 291 # "SELECTIONS" 
C_LISTSym = 292 # "LIST" 
C_SAPMinusSPOOLSym = 293 # "SAP-SPOOL" 
C_SPOOLSym = 294 # "SPOOL" 
C_PARAMETERSSym = 295 # "PARAMETERS" 
C_ARCHIVESym = 296 # "ARCHIVE" 
C_DYNPROSym = 297 # "DYNPRO" 
C_JOBSym = 298 # "JOB" 
C_RETURNSym = 299 # "RETURN" 
C_TRYSym = 300 # "TRY" 
C_CATCHSym = 301 # "CATCH" 
C_BEFORESym = 302 # "BEFORE" 
C_UNWINDSym = 303 # "UNWIND" 
C_CLEANUPSym = 304 # "CLEANUP" 
C_ENDTRYSym = 305 # "ENDTRY" 
C_ASSOCIATIONSym = 306 # "ASSOCIATION" 
C_TYPESSym = 307 # "TYPES" 
C_ENUMSym = 308 # "ENUM" 
C_STRUCTURESym = 309 # "STRUCTURE" 
C_BASESym = 310 # "BASE" 
C_MESHSym = 311 # "MESH" 
C_forSym = 312 # "for" 
C_SemicolonSym = 313 # ";" 
C_SETSym = 314 # "SET" 
C_WHILESym = 315 # "WHILE" 
C_VARYSym = 316 # "VARY" 
C_ENDWHILESym = 317 # "ENDWHILE" 
C_TASKSym = 318 # "TASK" 
C_NEWSym = 319 # "NEW" 
C_BACKGROUNDSym = 320 # "BACKGROUND" 
C_SEPARATESym = 321 # "SEPARATE" 
C_DESTINATIONSym = 322 # "DESTINATION" 
C_CALLINGSym = 323 # "CALLING" 
C_PERFORMINGSym = 324 # "PERFORMING" 
C_IMPORTINGSym = 325 # "IMPORTING" 
C_CHANGINGSym = 326 # "CHANGING" 
C_EXCEPTIONSSym = 327 # "EXCEPTIONS" 
C_errorUnderscoremessageSym = 328 # "error_message" 
C_systemUnderscorefailureSym = 329 # "system_failure" 
C_communicationUnderscorefaiSym = 330 # "communication_failure" 
C_resourceUnderscorefailureSym = 331 # "resource_failure" 
C_PARAMETERMinusTABLESym = 332 # "PARAMETER-TABLE" 
C_EXCEPTIONMinusTABLESym = 333 # "EXCEPTION-TABLE" 
C_IFSym = 334 # "IF" 
C_ELSEIFSym = 335 # "ELSEIF" 
C_ELSESym = 336 # "ELSE" 
C_ENDIFSym = 337 # "ENDIF" 
C_returnSym = 338 # "return" 
C_CLASSSym = 339 # "CLASS" 
C_DEFINITIONSym = 340 # "DEFINITION" 
C_DEFERREDSym = 341 # "DEFERRED" 
C_PUBLICSym = 342 # "PUBLIC" 
C_PROTECTEDSym = 343 # "PROTECTED" 
C_PRIVATESym = 344 # "PRIVATE" 
C_INHERITINGSym = 345 # "INHERITING" 
C_ABSTRACTSym = 346 # "ABSTRACT" 
C_FINALSym = 347 # "FINAL" 
C_CREATESym = 348 # "CREATE" 
C_ENABLEDSym = 349 # "ENABLED" 
C_TESTINGSym = 350 # "TESTING" 
C_RISKSym = 351 # "RISK" 
C_LEVELSym = 352 # "LEVEL" 
C_CRITICALSym = 353 # "CRITICAL" 
C_DANGEROUSSym = 354 # "DANGEROUS" 
C_HARMLESSSym = 355 # "HARMLESS" 
C_DURATIONSym = 356 # "DURATION" 
C_SHORTSym = 357 # "SHORT" 
C_MEDIUMSym = 358 # "MEDIUM" 
C_LONGSym = 359 # "LONG" 
C_GLOBALSym = 360 # "GLOBAL" 
C_FRIENDSSym = 361 # "FRIENDS" 
C_IMPLEMENTATIONSym = 362 # "IMPLEMENTATION" 
C_SECTIONSym = 363 # "SECTION" 
C_ENDCLASSSym = 364 # "ENDCLASS" 
C_METHODSym = 365 # "METHOD" 
C_ENDMETHODSym = 366 # "ENDMETHOD" 
C_METHODSSym = 367 # "METHODS" 
C_CLASSMinusMETHODSSym = 368 # "CLASS-METHODS" 
C_REDEFINITIONSym = 369 # "REDEFINITION" 
C_IGNORESym = 370 # "IGNORE" 
C_FAILSym = 371 # "FAIL" 
C_PREFERREDSym = 372 # "PREFERRED" 
C_PARAMETERSym = 373 # "PARAMETER" 
C_RETURNINGSym = 374 # "RETURNING" 
C_ADDSym = 375 # "ADD" 
C_THENSym = 376 # "THEN" 
C_UNTILSym = 377 # "UNTIL" 
C_GIVINGSym = 378 # "GIVING" 
C_ACCORDINGSym = 379 # "ACCORDING" 
C_ADDMinusCORRESPONDINGSym = 380 # "ADD-CORRESPONDING" 
C_ALIASESSym = 381 # "ALIASES" 
C_ASSERTSym = 382 # "ASSERT" 
C_SUBKEYSym = 383 # "SUBKEY" 
C_CONDITIONSym = 384 # "CONDITION" 
C_ASSIGNSym = 385 # "ASSIGN" 
C_COMPONENTSym = 386 # "COMPONENT" 
C_MinusGreaterSym = 387 # "->" 
C_EqualGreaterSym = 388 # "=>" 
C_INCREMENTSym = 389 # "INCREMENT" 
C_FIRSTSym = 390 # "FIRST" 
C_LASTSym = 391 # "LAST" 
C_ENDATSym = 392 # "ENDAT" 
C_BACKSym = 393 # "BACK" 
C_BREAKMinusPOINTSym = 394 # "BREAK-POINT" 
C_CALLSym = 395 # "CALL" 
C_CUSTOMERMinusFUNCTIONSym = 396 # "CUSTOMER-FUNCTION" 
C_DIALOGSym = 397 # "DIALOG" 
C_SKIPSym = 398 # "SKIP" 
C_PROCEDURESym = 399 # "PROCEDURE" 
C_RECEIVINGSym = 400 # "RECEIVING" 
C_FLUSHSym = 401 # "FLUSH" 
C_QUEUEMinusONLYSym = 402 # "QUEUE-ONLY" 
C_TRANSACTIONSym = 403 # "TRANSACTION" 
C_OPTIONSSym = 404 # "OPTIONS" 
C_MESSAGESSym = 405 # "MESSAGES" 
C_TRANSFORMATIONSym = 406 # "TRANSFORMATION" 
C_OBJECTSSym = 407 # "OBJECTS" 
C_SOURCESym = 408 # "SOURCE" 
C_XMLSym = 409 # "XML" 
C_AREASym = 410 # "AREA" 
C_BADISym = 411 # "BADI" 
C_CHECKSym = 412 # "CHECK" 
C_CLASSMinusDATASym = 413 # "CLASS-DATA" 
C_CLASSMinusEVENTSSym = 414 # "CLASS-EVENTS" 
C_CLASSMinusPOOLSym = 415 # "CLASS-POOL" 
C_CLEARSym = 416 # "CLEAR" 
C_NULLSym = 417 # "NULL" 
C_CLOSESym = 418 # "CLOSE" 
C_COLLECTSym = 419 # "COLLECT" 
C_COMMITSym = 420 # "COMMIT" 
C_WORKSym = 421 # "WORK" 
C_WAITSym = 422 # "WAIT" 
C_COMPUTESym = 423 # "COMPUTE" 
C_QuerySym = 424 # "?" 
C_CONDENSESym = 425 # "CONDENSE" 
C_NOMinusGAPSSym = 426 # "NO-GAPS" 
C_CONTROLSSym = 427 # "CONTROLS" 
C_TABLEVIEWSym = 428 # "TABLEVIEW" 
C_TABSTRIPSym = 429 # "TABSTRIP" 
C_CONVERTSym = 430 # "CONVERT" 
C_SORTABLESym = 431 # "SORTABLE" 
C_STAMPSym = 432 # "STAMP" 
C_DAYLIGHTSym = 433 # "DAYLIGHT" 
C_SAVINGSym = 434 # "SAVING" 
C_DEMANDSym = 435 # "DEMAND" 
C_CONTEXTSym = 436 # "CONTEXT" 
C_DESCRIBESym = 437 # "DESCRIBE" 
C_DISTANCESym = 438 # "DISTANCE" 
C_OUTPUTMinusLENGTHSym = 439 # "OUTPUT-LENGTH" 
C_HELPMinusIDSym = 440 # "HELP-ID" 
C_PAGESSym = 441 # "PAGES" 
C_FIRSTMinusLINESym = 442 # "FIRST-LINE" 
C_TOPMinusLINESSym = 443 # "TOP-LINES" 
C_TITLEMinusLINESSym = 444 # "TITLE-LINES" 
C_HEADMinusLINESSym = 445 # "HEAD-LINES" 
C_ENDMinusLINESSym = 446 # "END-LINES" 
C_KINDSym = 447 # "KIND" 
C_DETAILSym = 448 # "DETAIL" 
C_DIVIDESym = 449 # "DIVIDE" 
C_DIVIDEMinusCORRESPONDINGSym = 450 # "DIVIDE-CORRESPONDING" 
C_EDITORMinusCALLSym = 451 # "EDITOR-CALL" 
C_DISPLAYMinusMODESym = 452 # "DISPLAY-MODE" 
C_TITLESym = 453 # "TITLE" 
C_BACKUPSym = 454 # "BACKUP" 
C_ENDMinusOFMinusPAGESym = 455 # "END-OF-PAGE" 
C_ENDMinusOFMinusSELECTIONSym = 456 # "END-OF-SELECTION" 
C_EXITSym = 457 # "EXIT" 
C_SQLSym = 458 # "SQL" 
C_STEPMinusLOOPSym = 459 # "STEP-LOOP" 
C_EXPORTSym = 460 # "EXPORT" 
C_INTERNALSym = 461 # "INTERNAL" 
C_COMPRESSIONSym = 462 # "COMPRESSION" 
C_OFFSym = 463 # "OFF" 
C_EXTRACTSym = 464 # "EXTRACT" 
C_FIELDMinusGROUPSSym = 465 # "FIELD-GROUPS" 
C_FIELDMinusSYMBOLSSym = 466 # "FIELD-SYMBOLS" 
C_FINDSym = 467 # "FIND" 
C_OCCURRENCESym = 468 # "OCCURRENCE" 
C_OCCURRENCESSym = 469 # "OCCURRENCES" 
C_SUBSTRINGSym = 470 # "SUBSTRING" 
C_REGEXSym = 471 # "REGEX" 
C_MATCHSym = 472 # "MATCH" 
C_COUNTSym = 473 # "COUNT" 
C_RESULTSSym = 474 # "RESULTS" 
C_SUBMATCHESSym = 475 # "SUBMATCHES" 
C_COLORSym = 476 # "COLOR" 
C_COLUnderscoreBACKGROUNDSym = 477 # "COL_BACKGROUND" 
C_COLUnderscoreHEADINGSym = 478 # "COL_HEADING" 
C_COLUnderscoreNORMALSym = 479 # "COL_NORMAL" 
C_COLUnderscoreTOTALSym = 480 # "COL_TOTAL" 
C_COLUnderscoreKEYSym = 481 # "COL_KEY" 
C_COLUnderscorePOSITIVESym = 482 # "COL_POSITIVE" 
C_COLUnderscoreNEGATIVESym = 483 # "COL_NEGATIVE" 
C_COLUnderscoreGROUPSym = 484 # "COL_GROUP" 
C_INTENSIFIEDSym = 485 # "INTENSIFIED" 
C_INVERSESym = 486 # "INVERSE" 
C_HOTSPOTSym = 487 # "HOTSPOT" 
C_FRAMESSym = 488 # "FRAMES" 
C_RESETSym = 489 # "RESET" 
C_FUNCTIONMinusPOOLSym = 490 # "FUNCTION-POOL" 
C_GENERATESym = 491 # "GENERATE" 
C_SUBROUTINESym = 492 # "SUBROUTINE" 
C_POOLSym = 493 # "POOL" 
C_INCLUDESym = 494 # "INCLUDE" 
C_SHORTDUMPMinusIDSym = 495 # "SHORTDUMP-ID" 
C_GETSym = 496 # "GET" 
C_FILTERSSym = 497 # "FILTERS" 
C_FILTERMinusTABLESym = 498 # "FILTER-TABLE" 
C_BITSym = 499 # "BIT" 
C_ATTRIBUTESSym = 500 # "ATTRIBUTES" 
C_LOCALESym = 501 # "LOCALE" 
C_COUNTRYSym = 502 # "COUNTRY" 
C_MODIFIERSym = 503 # "MODIFIER" 
C_PFMinusSTATUSSym = 504 # "PF-STATUS" 
C_EXCLUDINGSym = 505 # "EXCLUDING" 
C_PROPERTYSym = 506 # "PROPERTY" 
C_RUNSym = 507 # "RUN" 
C_HIDESym = 508 # "HIDE" 
C_IMPORTSym = 509 # "IMPORT" 
C_MAJORMinusIDSym = 510 # "MAJOR-ID" 
C_MINORMinusIDSym = 511 # "MINOR-ID" 
C_ACCEPTINGSym = 512 # "ACCEPTING" 
C_PADDINGSym = 513 # "PADDING" 
C_TRUNCATIONSym = 514 # "TRUNCATION" 
C_BOUNDARIESSym = 515 # "BOUNDARIES" 
C_CHARMinusTOMinusHEXSym = 516 # "CHAR-TO-HEX" 
C_DIRECTORYSym = 517 # "DIRECTORY" 
C_RENAMINGSym = 518 # "RENAMING" 
C_SUFFIXSym = 519 # "SUFFIX" 
C_FOUNDSym = 520 # "FOUND" 
C_INFOTYPESSym = 521 # "INFOTYPES" 
C_PERSONSym = 522 # "PERSON" 
C_INITIALIZATIONSym = 523 # "INITIALIZATION" 
C_INSERTSym = 524 # "INSERT" 
C_VALUESSym = 525 # "VALUES" 
C_DUPLICATESym = 526 # "DUPLICATE" 
C_KEYSSym = 527 # "KEYS" 
C_ENTRYSym = 528 # "ENTRY" 
C_FIXEDMinusPOINTSym = 529 # "FIXED-POINT" 
C_ARITHMETICSym = 530 # "ARITHMETIC" 
C_UNICODESym = 531 # "UNICODE" 
C_ENABLINGSym = 532 # "ENABLING" 
C_INTERFACESym = 533 # "INTERFACE" 
C_ENDINTERFACESym = 534 # "ENDINTERFACE" 
C_LOADSym = 535 # "LOAD" 
C_INTERFACEMinusPOOLSym = 536 # "INTERFACE-POOL" 
C_INTERFACESSym = 537 # "INTERFACES" 
C_PARTIALLYSym = 538 # "PARTIALLY" 
C_IMPLEMENTEDSym = 539 # "IMPLEMENTED" 
C_LEAVESym = 540 # "LEAVE" 
C_LISTMinusPROCESSINGSym = 541 # "LIST-PROCESSING" 
C_LOADMinusOFMinusPROGRAMSym = 542 # "LOAD-OF-PROGRAM" 
C_LOCALSym = 543 # "LOCAL" 
C_LOGMinusPOINTSym = 544 # "LOG-POINT" 
C_MINIMUMSym = 545 # "MINIMUM" 
C_MODULESym = 546 # "MODULE" 
C_ENDMODULESym = 547 # "ENDMODULE" 
C_MULTIPLYSym = 548 # "MULTIPLY" 
C_MULTIPLYMinusCORRESPONDINGSym = 549 # "MULTIPLY-CORRESPONDING" 
C_NEWMinusLINESym = 550 # "NEW-LINE" 
C_NOMinusSCROLLINGSym = 551 # "NO-SCROLLING" 
C_SCROLLINGSym = 552 # "SCROLLING" 
C_NEWMinusPAGESym = 553 # "NEW-PAGE" 
C_WITHMinusTITLESym = 554 # "WITH-TITLE" 
C_NOMinusTITLESym = 555 # "NO-TITLE" 
C_WITHMinusHEADINGSym = 556 # "WITH-HEADING" 
C_NOMinusHEADINGSym = 557 # "NO-HEADING" 
C_NOMinusTOPOFPAGESym = 558 # "NO-TOPOFPAGE" 
C_PRINTSym = 559 # "PRINT" 
C_NEWMinusSECTIONSym = 560 # "NEW-SECTION" 
C_NODESSym = 561 # "NODES" 
C_OVERLAYSym = 562 # "OVERLAY" 
C_ONLYSym = 563 # "ONLY" 
C_PACKSym = 564 # "PACK" 
C_OBLIGATORYSym = 565 # "OBLIGATORY" 
C_NOMinusDISPLAYSym = 566 # "NO-DISPLAY" 
C_VISIBLESym = 567 # "VISIBLE" 
C_USERMinusCOMMANDSym = 568 # "USER-COMMAND" 
C_LISTBOXSym = 569 # "LISTBOX" 
C_RADIOBUTTONSym = 570 # "RADIOBUTTON" 
C_MODIFSym = 571 # "MODIF" 
C_LOWERSym = 572 # "LOWER" 
C_MATCHCODESym = 573 # "MATCHCODE" 
C_NODESym = 574 # "NODE" 
C_HELPMinusREQUESTSym = 575 # "HELP-REQUEST" 
C_VALUEMinusREQUESTSym = 576 # "VALUE-REQUEST" 
C_PATTERNSym = 577 # "PATTERN" 
C_PERFORMSym = 578 # "PERFORM" 
C_ROLLBACKSym = 579 # "ROLLBACK" 
C_PRINTMinusCONTROLSym = 580 # "PRINT-CONTROL" 
C_INDEXMinusLINESym = 581 # "INDEX-LINE" 
C_RANGESSym = 582 # "RANGES" 
C_RECEIVESym = 583 # "RECEIVE" 
C_REFRESHSym = 584 # "REFRESH" 
C_CONTROLSym = 585 # "CONTROL" 
C_REJECTSym = 586 # "REJECT" 
C_REPLACESym = 587 # "REPLACE" 
C_RESERVESym = 588 # "RESERVE" 
C_RESUMESym = 589 # "RESUME" 
C_RETRYSym = 590 # "RETRY" 
C_SCROLLSym = 591 # "SCROLL" 
C_COLUMNSym = 592 # "COLUMN" 
C_PLACESSym = 593 # "PLACES" 
C_FORWARDSym = 594 # "FORWARD" 
C_BACKWARDSym = 595 # "BACKWARD" 
C_SELECTMinusOPTIONSSym = 596 # "SELECT-OPTIONS" 
C_NOMinusEXTENSIONSym = 597 # "NO-EXTENSION" 
C_INTERVALSSym = 598 # "INTERVALS" 
C_OPTIONSym = 599 # "OPTION" 
C_SELECTIONSym = 600 # "SELECTION" 
C_LOWSym = 601 # "LOW" 
C_HIGHSym = 602 # "HIGH" 
C_TABSym = 603 # "TAB" 
C_BLANKSym = 604 # "BLANK" 
C_FILESym = 605 # "FILE" 
C_HANDLERSym = 606 # "HANDLER" 
C_INSTANCESSym = 607 # "INSTANCES" 
C_ACTIVATIONSym = 608 # "ACTIVATION" 
C_SCROLLMinusBOUNDARYSym = 609 # "SCROLL-BOUNDARY" 
C_MARGINSym = 610 # "MARGIN" 
C_IMMEDIATELYSym = 611 # "IMMEDIATELY" 
C_ANALYZERSym = 612 # "ANALYZER" 
C_CLOCKSym = 613 # "CLOCK" 
C_RESOLUTIONSym = 614 # "RESOLUTION" 
C_TITLEBARSym = 615 # "TITLEBAR" 
C_SHIFTSym = 616 # "SHIFT" 
C_CIRCULARSym = 617 # "CIRCULAR" 
C_DELETINGSym = 618 # "DELETING" 
C_LEADINGSym = 619 # "LEADING" 
C_TRAILINGSym = 620 # "TRAILING" 
C_STOPSym = 621 # "STOP" 
C_SUBTRACTSym = 622 # "SUBTRACT" 
C_SUBTRACTMinusCORRESPONDINGSym = 623 # "SUBTRACT-CORRESPONDING" 
C_SUMSym = 624 # "SUM" 
C_SUMMARYSym = 625 # "SUMMARY" 
C_SUMMINGSym = 626 # "SUMMING" 
C_SUPPLYSym = 627 # "SUPPLY" 
C_SUPPRESSSym = 628 # "SUPPRESS" 
C_SYNTAXMinusCHECKSym = 629 # "SYNTAX-CHECK" 
C_SWITCHSTATESSym = 630 # "SWITCHSTATES" 
C_TESTMinusINJECTIONSym = 631 # "TEST-INJECTION" 
C_ENDMinusTESTMinusINJECTIONSym = 632 # "END-TEST-INJECTION" 
C_TESTMinusSEAMSym = 633 # "TEST-SEAM" 
C_ENDMinusTESTMinusSEAMSym = 634 # "END-TEST-SEAM" 
C_TOPMinusOFMinusPAGESym = 635 # "TOP-OF-PAGE" 
C_DURINGSym = 636 # "DURING" 
C_LINEMinusSELECTIONSym = 637 # "LINE-SELECTION" 
C_TRANSFERSym = 638 # "TRANSFER" 
C_TRANSLATESym = 639 # "TRANSLATE" 
C_UPPERSym = 640 # "UPPER" 
C_TRUNCATESym = 641 # "TRUNCATE" 
C_TYPEMinusPOOLSym = 642 # "TYPE-POOL" 
C_TYPEMinusPOOLSSym = 643 # "TYPE-POOLS" 
C_ULINESym = 644 # "ULINE" 
C_UNASSIGNSym = 645 # "UNASSIGN" 
C_UNPACKSym = 646 # "UNPACK" 
C_SECONDSSym = 647 # "SECONDS" 
C_ASYNCHRONOUSSym = 648 # "ASYNCHRONOUS" 
C_TASKSSym = 649 # "TASKS" 
C_MESSAGINGSym = 650 # "MESSAGING" 
C_CHANNELSSym = 651 # "CHANNELS" 
C_PUSHSym = 652 # "PUSH" 
C_WINDOWSym = 653 # "WINDOW" 
C_SPLITSym = 654 # "SPLIT" 
C_BarBarSym = 655 # "||" 
C_EQUIVSym = 656 # "EQUIV" 
C_AndAndSym = 657 # "&&" 
C_BarSym = 658 # "|" 
C_UparrowSym = 659 # "^" 
C_AndSym = 660 # "&" 
C_LessGreaterSym = 661 # "<>" 
C_LessSym = 662 # "<" 
C_GreaterSym = 663 # ">" 
C_LessEqualSym = 664 # "<=" 
C_GreaterEqualSym = 665 # ">=" 
C_COSym = 666 # "CO" 
C_CNSym = 667 # "CN" 
C_CASym = 668 # "CA" 
C_NASym = 669 # "NA" 
C_CSSym = 670 # "CS" 
C_NSSym = 671 # "NS" 
C_BYTEMinusCOSym = 672 # "BYTE-CO" 
C_BYTEMinusCNSym = 673 # "BYTE-CN" 
C_BYTEMinusCASym = 674 # "BYTE-CA" 
C_BYTEMinusNASym = 675 # "BYTE-NA" 
C_BYTEMinusCSSym = 676 # "BYTE-CS" 
C_BYTEMinusNSSym = 677 # "BYTE-NS" 
C_LessLessSym = 678 # "<<" 
C_GreaterGreaterSym = 679 # ">>" 
C_MinusSym = 680 # "-" 
C_DIVSym = 681 # "DIV" 
C_PercentSym = 682 # "%" 
C_MODSym = 683 # "MOD" 
C_PlusPlusSym = 684 # "++" 
C_MinusMinusSym = 685 # "--" 
C_StarEqualSym = 686 # "*=" 
C_SlashEqualSym = 687 # "/=" 
C_PercentEqualSym = 688 # "%=" 
C_PlusEqualSym = 689 # "+=" 
C_MinusEqualSym = 690 # "-=" 
C_AndEqualSym = 691 # "&=" 
C_UparrowEqualSym = 692 # "^=" 
C_BarEqualSym = 693 # "|=" 
C_LessLessEqualSym = 694 # "<<=" 
C_GreaterGreaterEqualSym = 695 # ">>=" 
C_BangSym = 696 # "!" 
C_INSTANCESym = 697 # "INSTANCE" 
C_BOUNDSym = 698 # "BOUND" 
C_ASSIGNEDSym = 699 # "ASSIGNED" 
C_SUPPLIEDSym = 700 # "SUPPLIED" 
C_REQUESTEDSym = 701 # "REQUESTED" 
No_Sym = 702 # not 
C_PreProcessorSym = 703 # PreProcessor 


MAXT =	No_Sym 	# Max Terminals */
C_MAXT = MAXT


SYMS=[  
    "EOF",
    "identifier",
"number",
"hexnumber",
"string1",
"char",
"Colon",
"space1",
"(",
")",
"REPORT",
"NO",
"STANDARD",
"PAGE",
"HEADING",
"LINE-SIZE",
"LINE-COUNT",
"MESSAGE-ID",
"DEFINING",
"DATABASE",
"REDUCED",
"FUNCTIONALITY",
".",
"FUNCTION",
"ENDFUNCTION",
"ENDSELECT",
"FIELDS",
"DISTINCT",
"*",
",",
"FROM",
"AS",
"USING",
"CLIENT",
"SPECIFIED",
"~",
"~*",
"aggregate",
"INNER",
"LEFT",
"RIGHT",
"OUTER",
"CROSS",
"JOIN",
"ON",
"ORDER",
"BY",
"PRIMARY",
"KEY",
"ASCENDING",
"DESCENDING",
"INTO",
"APPENDING",
"CORRESPONDING",
"OF",
"TABLE",
"PACKAGE",
"SIZE",
"@DATA",
"SELECT",
"SINGLE",
"FOR",
"UPDATE",
"ALL",
"ENTRIES",
"IN",
"WHERE",
"GROUP",
"HAVING",
"UNION",
"EXTENDED",
"RESULT",
"@",
"CREATING",
"READER",
"LOCATOR",
"COLUMNS",
"OTHER",
"BLOB",
"CLOB",
"OFFSET",
"UP",
"TO",
"ROWS",
"BYPASSING",
"BUFFER",
"CONNECTION",
"+",
"WITH",
"ENDWITH",
"TABLES",
"MOVE",
"EXACT",
"?TO",
"PERCENTAGE",
"MOVE-CORRESPONDING",
"EXPANDING",
"NESTED",
"KEEPING",
"TARGET",
"APPEND",
"INITIAL",
"LINE",
"[",
"]",
"SORTED",
"ASSIGNING",
"CASTING",
"REFERENCE",
"CONCATENATE",
"CHARACTER",
"BYTE",
"MODE",
"SEPARATED",
"RESPECTING",
"BLANKS",
"SEARCH",
"STARTING",
"AT",
"ENDING",
"ABBREVIATED",
"AND",
"MARK",
"RAISE",
"EVENT",
"EXPORTING",
"RESUMABLE",
"EXCEPTION",
"TYPE",
"MESSAGE",
"ID",
"NUMBER",
"DISPLAY",
"LIKE",
"RAISING",
"=",
"INDEX",
"TEXT",
"WITHOUT",
"MEMBERS",
"LOOP",
"TRANSPORTING",
"VERSION",
"SCREEN",
"ENDLOOP",
"DECIMALS",
"LOB",
"HANDLE",
"BOXED",
"REF",
"EMPTY",
"HEADER",
"UNIQUE",
"NON-UNIQUE",
"primary_key",
"ALIAS",
"COMPONENTS",
"DEFAULT",
"HASHED",
"RANGE",
"DATA",
"STATICS",
"BEGIN",
"COMMON",
"PART",
"READ-ONLY",
"OCCURS",
"END",
"VALID",
"BETWEEN",
"VALUE",
"IS",
"CONSTANTS",
"WRITE",
"/",
"**",
"UNDER",
"NO-GAP",
"LEFT-JUSTIFIED",
"CENTERED",
"RIGHT-JUSTIFIED",
"EXPONENT",
"NO-GROUPING",
"NO-SIGN",
"NO-ZERO",
"CURRENCY",
"ROUND",
"UNIT",
"ENVIRONMENT",
"TIME",
"FORMAT",
"ZONE",
"STYLE",
"EDIT",
"MASK",
"DD/MM/YY",
"MM/DD/YY",
"DD/MM/YYYY",
"MM/DD/YYYY",
"DDMMYY",
"MMDDYY",
"YYMMDD",
"CHECKBOX",
"ICON",
"SYMBOL",
"QUICKINFO",
"CONTINUE",
"CASE",
"WHEN",
"OR",
"OTHERS",
"ENDCASE",
"FIELD",
"DUMMY",
"AUTHORITY-CHECK",
"OBJECT",
"USER",
"DELETE",
"DATASET",
"ADJACENT",
"DUPLICATES",
"COMPARING",
"MEMORY",
"SHARED",
"VARYING",
"NEXT",
"DO",
"TIMES",
"ENDDO",
"OPTIONAL",
"EVENTS",
"MODIFY",
"CURRENT",
"CHANGE",
"ENDON",
"OPEN",
"CURSOR",
"HOLD",
"INPUT",
"OUTPUT",
"BINARY",
"ENCODING",
"SKIPPING",
"BYTE-ORDER",
"NON-UNICODE",
"NATIVE",
"SMART",
"UNIX",
"WINDOWS",
"LINEFEED",
"LEGACY",
"BIG",
"LITTLE",
"ENDIAN",
"CODE",
"POSITION",
"FILTER",
"IGNORING",
"CONVERSION",
"ERRORS",
"REPLACEMENT",
"FETCH",
"BOUNDS",
"PROVIDE",
"INCLUDING",
"GAPS",
"ENDPROVIDE",
"READ",
"MAXIMUM",
"ACTUAL",
"WIDTH",
"TEXTPOOL",
"LANGUAGE",
"SORT",
"SUBMIT",
"SELECTION-SCREEN",
"VIA",
"SELECTION-SET",
"SELECTION-SETS",
"PROGRAM",
"SELECTION-TABLE",
"EQ",
"NE",
"CP",
"NP",
"GE",
"LT",
"LE",
"GT",
"NOT",
"FREE",
"SELECTIONS",
"LIST",
"SAP-SPOOL",
"SPOOL",
"PARAMETERS",
"ARCHIVE",
"DYNPRO",
"JOB",
"RETURN",
"TRY",
"CATCH",
"BEFORE",
"UNWIND",
"CLEANUP",
"ENDTRY",
"ASSOCIATION",
"TYPES",
"ENUM",
"STRUCTURE",
"BASE",
"MESH",
"for",
";",
"SET",
"WHILE",
"VARY",
"ENDWHILE",
"TASK",
"NEW",
"BACKGROUND",
"SEPARATE",
"DESTINATION",
"CALLING",
"PERFORMING",
"IMPORTING",
"CHANGING",
"EXCEPTIONS",
"error_message",
"system_failure",
"communication_failure",
"resource_failure",
"PARAMETER-TABLE",
"EXCEPTION-TABLE",
"IF",
"ELSEIF",
"ELSE",
"ENDIF",
"return",
"CLASS",
"DEFINITION",
"DEFERRED",
"PUBLIC",
"PROTECTED",
"PRIVATE",
"INHERITING",
"ABSTRACT",
"FINAL",
"CREATE",
"ENABLED",
"TESTING",
"RISK",
"LEVEL",
"CRITICAL",
"DANGEROUS",
"HARMLESS",
"DURATION",
"SHORT",
"MEDIUM",
"LONG",
"GLOBAL",
"FRIENDS",
"IMPLEMENTATION",
"SECTION",
"ENDCLASS",
"METHOD",
"ENDMETHOD",
"METHODS",
"CLASS-METHODS",
"REDEFINITION",
"IGNORE",
"FAIL",
"PREFERRED",
"PARAMETER",
"RETURNING",
"ADD",
"THEN",
"UNTIL",
"GIVING",
"ACCORDING",
"ADD-CORRESPONDING",
"ALIASES",
"ASSERT",
"SUBKEY",
"CONDITION",
"ASSIGN",
"COMPONENT",
"->",
"=>",
"INCREMENT",
"FIRST",
"LAST",
"ENDAT",
"BACK",
"BREAK-POINT",
"CALL",
"CUSTOMER-FUNCTION",
"DIALOG",
"SKIP",
"PROCEDURE",
"RECEIVING",
"FLUSH",
"QUEUE-ONLY",
"TRANSACTION",
"OPTIONS",
"MESSAGES",
"TRANSFORMATION",
"OBJECTS",
"SOURCE",
"XML",
"AREA",
"BADI",
"CHECK",
"CLASS-DATA",
"CLASS-EVENTS",
"CLASS-POOL",
"CLEAR",
"NULL",
"CLOSE",
"COLLECT",
"COMMIT",
"WORK",
"WAIT",
"COMPUTE",
"?",
"CONDENSE",
"NO-GAPS",
"CONTROLS",
"TABLEVIEW",
"TABSTRIP",
"CONVERT",
"SORTABLE",
"STAMP",
"DAYLIGHT",
"SAVING",
"DEMAND",
"CONTEXT",
"DESCRIBE",
"DISTANCE",
"OUTPUT-LENGTH",
"HELP-ID",
"PAGES",
"FIRST-LINE",
"TOP-LINES",
"TITLE-LINES",
"HEAD-LINES",
"END-LINES",
"KIND",
"DETAIL",
"DIVIDE",
"DIVIDE-CORRESPONDING",
"EDITOR-CALL",
"DISPLAY-MODE",
"TITLE",
"BACKUP",
"END-OF-PAGE",
"END-OF-SELECTION",
"EXIT",
"SQL",
"STEP-LOOP",
"EXPORT",
"INTERNAL",
"COMPRESSION",
"OFF",
"EXTRACT",
"FIELD-GROUPS",
"FIELD-SYMBOLS",
"FIND",
"OCCURRENCE",
"OCCURRENCES",
"SUBSTRING",
"REGEX",
"MATCH",
"COUNT",
"RESULTS",
"SUBMATCHES",
"COLOR",
"COL_BACKGROUND",
"COL_HEADING",
"COL_NORMAL",
"COL_TOTAL",
"COL_KEY",
"COL_POSITIVE",
"COL_NEGATIVE",
"COL_GROUP",
"INTENSIFIED",
"INVERSE",
"HOTSPOT",
"FRAMES",
"RESET",
"FUNCTION-POOL",
"GENERATE",
"SUBROUTINE",
"POOL",
"INCLUDE",
"SHORTDUMP-ID",
"GET",
"FILTERS",
"FILTER-TABLE",
"BIT",
"ATTRIBUTES",
"LOCALE",
"COUNTRY",
"MODIFIER",
"PF-STATUS",
"EXCLUDING",
"PROPERTY",
"RUN",
"HIDE",
"IMPORT",
"MAJOR-ID",
"MINOR-ID",
"ACCEPTING",
"PADDING",
"TRUNCATION",
"BOUNDARIES",
"CHAR-TO-HEX",
"DIRECTORY",
"RENAMING",
"SUFFIX",
"FOUND",
"INFOTYPES",
"PERSON",
"INITIALIZATION",
"INSERT",
"VALUES",
"DUPLICATE",
"KEYS",
"ENTRY",
"FIXED-POINT",
"ARITHMETIC",
"UNICODE",
"ENABLING",
"INTERFACE",
"ENDINTERFACE",
"LOAD",
"INTERFACE-POOL",
"INTERFACES",
"PARTIALLY",
"IMPLEMENTED",
"LEAVE",
"LIST-PROCESSING",
"LOAD-OF-PROGRAM",
"LOCAL",
"LOG-POINT",
"MINIMUM",
"MODULE",
"ENDMODULE",
"MULTIPLY",
"MULTIPLY-CORRESPONDING",
"NEW-LINE",
"NO-SCROLLING",
"SCROLLING",
"NEW-PAGE",
"WITH-TITLE",
"NO-TITLE",
"WITH-HEADING",
"NO-HEADING",
"NO-TOPOFPAGE",
"PRINT",
"NEW-SECTION",
"NODES",
"OVERLAY",
"ONLY",
"PACK",
"OBLIGATORY",
"NO-DISPLAY",
"VISIBLE",
"USER-COMMAND",
"LISTBOX",
"RADIOBUTTON",
"MODIF",
"LOWER",
"MATCHCODE",
"NODE",
"HELP-REQUEST",
"VALUE-REQUEST",
"PATTERN",
"PERFORM",
"ROLLBACK",
"PRINT-CONTROL",
"INDEX-LINE",
"RANGES",
"RECEIVE",
"REFRESH",
"CONTROL",
"REJECT",
"REPLACE",
"RESERVE",
"RESUME",
"RETRY",
"SCROLL",
"COLUMN",
"PLACES",
"FORWARD",
"BACKWARD",
"SELECT-OPTIONS",
"NO-EXTENSION",
"INTERVALS",
"OPTION",
"SELECTION",
"LOW",
"HIGH",
"TAB",
"BLANK",
"FILE",
"HANDLER",
"INSTANCES",
"ACTIVATION",
"SCROLL-BOUNDARY",
"MARGIN",
"IMMEDIATELY",
"ANALYZER",
"CLOCK",
"RESOLUTION",
"TITLEBAR",
"SHIFT",
"CIRCULAR",
"DELETING",
"LEADING",
"TRAILING",
"STOP",
"SUBTRACT",
"SUBTRACT-CORRESPONDING",
"SUM",
"SUMMARY",
"SUMMING",
"SUPPLY",
"SUPPRESS",
"SYNTAX-CHECK",
"SWITCHSTATES",
"TEST-INJECTION",
"END-TEST-INJECTION",
"TEST-SEAM",
"END-TEST-SEAM",
"TOP-OF-PAGE",
"DURING",
"LINE-SELECTION",
"TRANSFER",
"TRANSLATE",
"UPPER",
"TRUNCATE",
"TYPE-POOL",
"TYPE-POOLS",
"ULINE",
"UNASSIGN",
"UNPACK",
"SECONDS",
"ASYNCHRONOUS",
"TASKS",
"MESSAGING",
"CHANNELS",
"PUSH",
"WINDOW",
"SPLIT",
"||",
"EQUIV",
"&&",
"|",
"^",
"&",
"<>",
"<",
">",
"<=",
">=",
"CO",
"CN",
"CA",
"NA",
"CS",
"NS",
"BYTE-CO",
"BYTE-CN",
"BYTE-CA",
"BYTE-NA",
"BYTE-CS",
"BYTE-NS",
"<<",
">>",
"-",
"DIV",
"%",
"MOD",
"++",
"--",
"*=",
"/=",
"%=",
"+=",
"-=",
"&=",
"^=",
"|=",
"<<=",
">>=",
"!",
"INSTANCE",
"BOUND",
"ASSIGNED",
"SUPPLIED",
"REQUESTED",
"not",
"PreProcessor",

]
