# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
def test()

   a = in_source_bo_node_name = if_fia_acc_adjustment_run.co_bo_node.root
   mo_lcp_bo.retrieve_default_node_values(_e:{
      "in_association_name" => ls_attribute_map.core_bo_node_name,
      "in_source_bo_node_name" => if_fia_acc_adjustment_run.co_bo_node.root,
      "in_source_node_id" => mv_eco_root_node_id,
   })


end


