# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
def test()

   mo_mdro_schedule_immediately.schedule_immediately(_i:{
      "et_messages" => lt_message,
      "et_mdro_root_to_bgjobsch_map" => lt_mdro_root_to_bgjobsch_map,
   }, _e:{
      "io_facade" => me.mo_provider_context.get_lcp_facade(),
   })

end


