# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

def test()


   SORT fs_adapted_update_notif.affected_associations
   abap("DELETE ADJACENT DUPLICATES FROM fs_adapted_update_notif.affected_associations")

end


