# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module Abap


   abap=Abap
   module_function
   Abap_true = 'X'
   def abap_true;'X';  end
   Abap_false = ' '
   def abap_false;' ';  end
   Abap_undefined = '-'
   def abap_undefined;'-';  end
   Abap_on = 'X'
   def abap_on;'X';  end
   Abap_off = ' '
   def abap_off;' ';  end
   Abap_max_abs_type_name_ln = 200
   def abap_max_abs_type_name_ln;200;  end
   Abap_max_class_name_ln = 30
   def abap_max_class_name_ln;30;  end
   Abap_max_intf_name_ln = 30
   def abap_max_intf_name_ln;30;  end
   Abap_max_comp_name_ln = 30
   def abap_max_comp_name_ln;30;  end
   Abap_max_key_name_ln = 255
   def abap_max_key_name_ln;255;  end
   Abap_max_class_comp_name_ln = 61
   def abap_max_class_comp_name_ln;61;  end
   Abap_max_edit_mask_ln = 7
   def abap_max_edit_mask_ln;7;  end
   Abap_max_help_id_ln = 62
   def abap_max_help_id_ln;62;  end
   Abap_max_db_string_ln = 536870912
   def abap_max_db_string_ln;536870912;  end
   Abap_max_db_rawstring_ln = 1073741824
   def abap_max_db_rawstring_ln;1073741824;  end

end
