# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

class Abc


   def if_esf_provider_init_i_init(*_a,_i:nil,_e:nil,_b:nil)



      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      #var(_i) if _i
      var(_i) if _i;var(_e) if _e;_i.each{|k,v|eval("#{k}=v");varset(k, v)} if _i
      _e.each{|k,v|v=_b.local_variable_get(v.to_sym);eval("#{k}=v");varset(k, v)} if _e
      ###################################



      a = If_sample::Co_bo_node.root






      ###################################
      # setup exporting
      #_exp = {}
      # _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      #return {:exp=>_exp}
      _e.each{|k,v|_b.local_variable_set(v.to_sym, eval("#{k}"))} if _e && _b
      ###################################


   end


end
