# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
class Abc


   def if_esf_provider_access_i_retrieve1(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lt_requested_core_attr = nil # sesf_string_tab.new






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   def if_esf_provider_access_i_retrieve(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lt_requested_core_attr = nil # sesf_string_tab.new

      lt_eco_attr_for_cur_core_node = nil # sesf_string_tab.new

      a = b





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end


end
