# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
require_relative "cl_a1s_service_provider_eco.rb"

class Cl_a1fia_common_eco < Cl_a1s_service_provider_eco

   # methods IF_ESF_PROVIDER_ACCESS~MODIFY
   #     redefinition .
   #

   def if_esf_provider_access_i_modify(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      if @mv_do_retrieve_check == abap_true
         @mv_do_retrieve_check = abap_false





      end

      super.if_esf_provider_access_i_modify(_i:{
         "in_change_handler" => in_change_handler,
         "in_message_handler" => in_message_handler,
      })






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods IF_ESF_PROVIDER_ACCESS~RETRIEVE
   #     redefinition .
   #

   def if_esf_provider_access_i_retrieve(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lt_message = nil # cm_esi_root::Tt_esi_root.new

      lx_esf_core_service = nil # cx_esf_core_service.new

      super.if_esf_provider_access_i_retrieve(_i:{
         "in_bo_node_name" => in_bo_node_name,
         "in_node_ids" => in_node_ids,
         "in_requested_image" => in_requested_image,
         "in_edit_mode" => in_edit_mode,
         "in_requested_attributes" => in_requested_attributes,
         "in_message_handler" => in_message_handler,
         "in_buffer_sync_handler" => in_buffer_sync_handler,
      }, _e:{
         "out_data" => out_data,
         "out_failed_node_ids" => out_failed_node_ids,
      })

      if @mv_do_retrieve_check == abap_true && in_requested_image == If_esf_types::Co_image_transactional_buffer && lines != lines
         begin
            @mo_adaptation_handler.check(_i:{
               "out_messages" => lt_message,
            }, _e:{
               "in_bo_node_name" => in_bo_node_name,
               "in_node_ids" => in_node_ids,
               "in_check_scope" => if_esf_types::Co_check_scope_substructure,
            })


         rescue cx_esf_core_service=>lx_esf_core_service
            raise cx_fatal_exception.new


         end

         if lt_message.isNotINITIAL()
            @mo_message_manager.add_messages(lt_message)





         end


         @mv_do_retrieve_check = abap_false





      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods IF_ESF_PROVIDER_ACCESS~RETRIEVE_ROOT_NODE_ID
   #     redefinition .
   #

   def if_esf_provider_access_i_retrieve_root_node_id(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lx_bsa_runtime = nil # cx_bsa_runtime.new

      lx_root = nil # cx_root.new

      begin
         if @mo_rnid_manager.mv_skip_rnid_manager == abap_true
            if use_heuristic_for_rrnid == abap_true
               heuristic_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })




            elsif use_delegation_for_rrnid == abap_true
               delegation_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })


            elsif use_callback_for_rrnid == abap_true
               callback_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })


            else
               @mo_adaptation_handler.retrieve_root_node_id(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })



            end

            #*-----------END of OLD implementation ----------*



         else
            if @mo_rnid_manager.is_skipped.isINITIAL()
               super.if_esf_provider_access_i_retrieve_root_node_id(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })




            elsif use_heuristic_for_rrnid == abap_true
               heuristic_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })


            elsif use_delegation_for_rrnid == abap_true
               delegation_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })


            elsif use_callback_for_rrnid == abap_true
               callback_rrnid(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })


            else
               super.if_esf_provider_access_i_retrieve_root_node_id(_i:{
                  "out_links" => out_links,
               }, _e:{
                  "in_bo_node_name" => in_bo_node_name,
                  "in_node_ids" => in_node_ids,
                  "in_requested_image" => in_requested_image,
               })



            end



         end


      rescue cx_root=>lx_root
         handle_error_adaptation_hdlr(ix_exception:lx_bsa_runtime)

         handle_error(ix_exception:lx_root)


      end





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods IF_ESF_PROVIDER_ACTION~EXECUTE_ACTION
   #     redefinition .
   #

   def if_esf_provider_action_i_execute_action(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      if @mv_do_retrieve_check == abap_true
         @mv_do_retrieve_check = abap_false





      end

      @ms_execute_action_parameter.bo_node_name = in_bo_node_name

      @ms_execute_action_parameter.action_name = in_action_name

      @ms_execute_action_parameter.referencing_node_elements = in_referencing_node_elements

      if ! in_action_parameters.isINITIAL()


         assign(to:lv_action_parameters)

         lv_action_parameters = in_action_parameters





      end

      super.if_esf_provider_action_i_execute_action(_i:{
         "in_bo_node_name" => in_bo_node_name,
         "in_action_name" => in_action_name,
         "in_node_ids" => in_node_ids,
         "in_action_parameters" => in_action_parameters,
         "in_referencing_node_elements" => in_referencing_node_elements,
         "in_change_handler" => in_change_handler,
         "in_message_handler" => in_message_handler,
      })






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods IF_ESF_PROVIDER_INIT~INIT
   #     redefinition .
   #

   def if_esf_provider_init_i_init(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      super.if_esf_provider_init_i_init(_e:{
         "in_provider_context" => in_provider_context,
         "in_bo_name" => in_bo_name,
      }, _c:{
         "inout_preferred_trx_pattern" => inout_preferred_trx_pattern,
      })

      @mo_provider_context = in_provider_context






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods IF_ESF_PROVIDER_TRANSACT_CTRL~ON_AFTER_SAVE_TRANSACTION
   #     redefinition .

   def if_esf_provider_transact_ctrl_i_on_after_save_transaction(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      super.if_esf_provider_transact_ctrl_i_on_after_save_transaction(_i:{
         "in_rejected" => in_rejected,
      })

      #* remove last action for next save cycle

      clear(id:@ms_execute_action_parameter)





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods ADD_NODE_FOR_CALLBACK_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING .
   #

   def add_node_for_callback_rrnid(iv_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      abap("insert iv_bo_node_name into TABLE mt_callback_bo_node_name")
      if @mo_rnid_manager.isBOUND()
         @mo_rnid_manager.exclude(iv_node_name:iv_bo_node_name)





      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods ADD_NODE_FOR_HEURISTIC_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING .
   #

   def add_node_for_heuristic_rrnid(iv_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      abap("insert iv_bo_node_name into TABLE mt_heuristic_bo_node_name")
      if @mo_rnid_manager.isBOUND()
         @mo_rnid_manager.include(iv_node_name:iv_bo_node_name)





      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods ADD_NODE_FOR_DELEGATION_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING
   #       !IV_CORE_BO_NAME type STRING
   #       !IV_CORE_BO_NODE_NAME type STRING .
   #

   def add_node_for_delegation_rrnid(iv_core_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      ls_lcp_bo_node_name = nil # ty_lcp_bo_node_name.new

      ls_lcp_bo_node_name.bo_node_name = iv_bo_node_name

      ls_lcp_bo_node_name.core_bo_name = iv_core_bo_name

      ls_lcp_bo_node_name.core_bo_node_name = iv_core_bo_node_name

      abap("INSERT ls_lcp_bo_node_name INTO TABLE mt_lcp_bo_node_name")
      if @mo_rnid_manager.isBOUND()
         @mo_rnid_manager.exclude(iv_node_name:iv_bo_node_name)





      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods CALLBACK_RRNID
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
   #       !IN_REQUESTED_IMAGE type IF_ESF_TYPES=>TY_IMAGE default IF_ESF_TYPES=>CO_IMAGE_TRANSACTIONAL_BUFFER
   #     exporting
   #       !OUT_LINKS type SESF_ASSOCIATION_LINK_TAB
   #     raising
   #       CX_ESF_CORE_SERVICE .
   #

   def callback_rrnid(in_requested_image:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      assert(o:1 == 0)





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods DISABLE_RETRIEVE_CHECK .

   def disable_retrieve_check(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      @mv_do_retrieve_check = abap_false






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods USE_CALLBACK_FOR_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING
   #     returning
   #       value(RV_RESULT) type BOOLEAN .
   #

   def use_callback_for_rrnid(iv_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      read_table(id:@mt_callback_bo_node_name, from:iv_bo_node_name)
      if sy.subrc == 0
         rv_result = abap_true




      else
         rv_result = abap_false



      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods USE_DELEGATION_FOR_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING
   #     returning
   #       value(RV_RESULT) type BOOLEAN .
   #

   def use_delegation_for_rrnid(iv_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      read_table(id:@mt_lcp_bo_node_name)
      if sy.subrc == 0
         rv_result = abap_true




      else
         rv_result = abap_false



      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods USE_HEURISTIC_FOR_RRNID
   #     importing
   #       !IV_BO_NODE_NAME type STRING
   #     returning
   #       value(RV_RESULT) type BOOLEAN .
   #

   def use_heuristic_for_rrnid(iv_bo_node_name:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      read_table(id:@mt_heuristic_bo_node_name, from:iv_bo_node_name)
      if sy.subrc == 0
         rv_result = abap_true




      else
         rv_result = abap_false



      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods HEURISTIC_RRNID
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
   #       !IN_REQUESTED_IMAGE type IF_ESF_TYPES=>TY_IMAGE default IF_ESF_TYPES=>CO_IMAGE_TRANSACTIONAL_BUFFER
   #     exporting
   #       !OUT_LINKS type SESF_ASSOCIATION_LINK_TAB
   #     raising
   #       CX_ESF_CORE_SERVICE .
   #

   def heuristic_rrnid(in_requested_image:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lv_node_id = nil # sesf_bo_node_id.new

      lv_node_id_determined = nil # boolean.new

      ls_origin_location = nil # cm_esi_root::Ty_message_location.new

      lo_message = nil # cm_a1fia_common_eco.new


      lv_root_node_name = nil # string.new

      lv_bo_name = nil # string.new

      lt_out_failed_node_id = nil # sesf_bo_node_id_tab.new

      lrt_core_bo_out_data = nil # data.new

      lt_requested_attributes = nil # sesf_string_tab.new


      lv_root_node_name = if_a1s_service_provider_eco_i_get_bo_root_node_name()

      lv_bo_name = if_a1s_service_provider_eco_i_get_bo_name()

      if in_bo_node_name == lv_root_node_name
         lrt_core_bo_out_data = @mo_provider_context.get_lcp_facade().get_bo_node_table_container(in_bo_name:lv_bo_name, in_bo_node_name:lv_root_node_name)



         assign(to:lt_core_bo_out_data)

         abap("INSERT if_esf_types => co_node_id_proxy_name INTO TABLE lt_requested_attributes")


         @mo_adaptation_handler.if_esf_lcp_i_retrieve(_i:{
            "in_bo_node_name" => in_bo_node_name,
            "in_node_ids" => in_node_ids,
            "in_edit_mode" => if_esf_types::Co_read_only,
            "in_requested_image" => in_requested_image,
            "in_requested_attributes" => lt_requested_attributes,
         }, _e:{
            "out_failed_node_ids" => lt_out_failed_node_id,
            "out_data" => lt_core_bo_out_data,
         })



         if lines == 0
            lt_out_links = if_a1fia_common_eco_i_source_to_target_mapping(in_node_ids)





         end



      else
         @mo_adaptation_handler.get_first_retrved_root_node_id(_i:{
            "ev_first_ret_data_root_node_id" => lv_node_id,
            "ev_first_root_id_determined" => lv_node_id_determined,
         })

         if lv_node_id_determined == abap_false || ( lv_node_id.isINITIAL() && lv_node_id_determined == abap_true )
            ls_origin_location.bo_name = lv_bo_name





            @mo_message_manager.add_message(lo_message)




         else
            if if_a1fia_common_eco_i_check_root_node_existence == abap_true
               loop(at:in_node_ids){
                  ls_link.source_node_id = ls_node_id



                  ls_link.target_node_id = lv_node_id



                  append(from:ls_link, to:lt_out_links)

               }



            end



         end



      end

      out_links = lt_out_links






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end
   # methods DELEGATION_RRNID
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
   #       !IN_REQUESTED_IMAGE type IF_ESF_TYPES=>TY_IMAGE default IF_ESF_TYPES=>CO_IMAGE_TRANSACTIONAL_BUFFER
   #     exporting
   #       !OUT_LINKS type SESF_ASSOCIATION_LINK_TAB
   #     raising
   #       CX_ESF_CORE_SERVICE .

   def delegation_rrnid(in_requested_image:nil,_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lo_lcp = nil # if_esf_lcp.new

      read_table(id:@mt_lcp_bo_node_name)
      assert(o:ls_lcp_bo_node_name.isASSIGNED())
      lo_lcp = @mo_adaptation_handler.get_lcp(ls_lcp_bo_node_name.core_bo_name)

      lo_lcp.retrieve_root_node_id(_i:{
         "in_bo_node_name" => ls_lcp_bo_node_name.core_bo_node_name,
         "in_node_ids" => in_node_ids,
         "in_requested_image" => in_requested_image,
      }, _e:{
         "out_links" => out_links,
      })






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   def if_a1fia_common_eco_i_check_root_node_existence(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lt_node_id = nil # sesf_bo_node_id_tab.new

      lt_out_links = nil # sesf_association_link_tab.new

      abap("INSERT iv_node_id INTO TABLE lt_node_id")
      if_esf_provider_access_i_retrieve_root_node_id(_i:{
         "in_bo_node_name" => if_a1s_service_provider_eco_i_get_bo_root_node_name(),
         "in_node_ids" => lt_node_id,
         "in_requested_image" => iv_requested_image,
      }, _e:{
         "out_links" => lt_out_links,
      })

      if lines > 0
         rv_exists = abap_true




      else
         rv_exists = abap_false



      end






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   def if_a1fia_common_eco_i_get_last_executed_action(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      rs_execute_action_parameter = @ms_execute_action_parameter






      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   def if_a1fia_common_eco_i_raise_stop_save_message(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################



      lo_ex_message = nil # cx_esf_message_handler.new

      lo_message = nil # cm_esi_t100_adapter.new

      ls_msg = nil # symsg.new

      ls_orig_loc = nil # cm_esi_root::Ty_message_location.new

      lt_out_messages = nil # cm_esi_root::Tt_esi_root.new

      ls_orig_loc.bo_name = if_a1s_service_provider_eco_i_get_bo_name()

      ls_msg.msgno = '103'

      ls_msg.msgty = 'E'

      ls_msg.msgid = 'A1FIA_ACCOUNTING'

      lo_message = cm_esi_t100_adapter::Create(symptom:cl_esi_message_symptom_code::Co_bo_inconsistency, lifetime:cm_esi_root::Co_lifetime_transition, origin_location:ls_orig_loc, symsg:ls_msg)

      append(from:lo_message, to:lt_out_messages)
      begin
         io_message_handler.add_messages(_i:{
            "in_messages" => lt_out_messages,
         })


      rescue cx_esf_message_handler=>lo_ex_message
         raise cx_fatal_exception.new


      end





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   def if_a1fia_common_eco_i_source_to_target_mapping(_i:nil,_e:nil)


      ###################################
      # setup importing parameter
      #   _i.each{|k,v| eval("#{k} = #{v}")} if _i
      #  _i.each{|k,v| v = "\"#{v}\"" if v.is_a?(String);eval("#{k} = #{v}")} if _i
      var(_i) if _i
      ###################################




      loop(at:it_node_id, into:ls_link.source_node_id){
         ls_link.target_node_id = ls_link.source_node_id



         append(from:ls_link, to:rt_out_link)

      }





      ###################################
      # setup exporting
      _exp = {}
      _e.each{|k,v| eval("_exp['#{v}'] = #{k}")} if _e

      return {:exp=>_exp}
      ###################################


   end

   @mo_provider_context = nil # if_esf_provider_context.new
   @ms_execute_action_parameter = nil # if_a1fia_common_eco::Ty_execute_action_parameter.new
   @mt_lcp_bo_node_name = nil # tt_lcp_bo_node_name.new
   @mt_callback_bo_node_name = nil # tt_heuristic_bo_node_name.new
   @mt_heuristic_bo_node_name = nil # tt_heuristic_bo_node_name.new
   @mv_do_retrieve_check = nil # sesf_boolean.new

end
