# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module Ib


   ib=Ib
   Co_bo_name = 'A1FIA_AAR_CREATE_QAF_ECO'
   def co_bo_name;'A1FIA_AAR_CREATE_QAF_ECO';  end
   module Co_bo_node
      module_function
      Bupa = 'BUPA'
      def bupa;'BUPA';  end
      Company = 'COMPANY'
      def company;'COMPANY';  end
      Cost_centre = 'COST_CENTRE'
      def cost_centre;'COST_CENTRE';  end
   end

end
