# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_a1fia_aar_create_qaf_eco


   if_a1fia_aar_create_qaf_eco=If_a1fia_aar_create_qaf_eco
   Co_bo_name = 'A1FIA_AAR_CREATE_QAF_ECO'
   def co_bo_name;'A1FIA_AAR_CREATE_QAF_ECO';  end
   module Co_bo_node
      module_function
      Bupa = 'BUPA'
      def bupa;'BUPA';  end
      Company = 'COMPANY'
      def company;'COMPANY';  end
      Cost_centre = 'COST_CENTRE'
      def cost_centre;'COST_CENTRE';  end
      Cust_ser_org = 'CUST_SER_ORG'
      def cust_ser_org;'CUST_SER_ORG';  end
      Fav_cost_object = 'FAV_COST_OBJECT'
      def fav_cost_object;'FAV_COST_OBJECT';  end
      Fcre_root = 'FCRE_ROOT'
      def fcre_root;'FCRE_ROOT';  end
      Fcre_sel_by_bupa = 'FCRE_SEL_BY_BUPA'
      def fcre_sel_by_bupa;'FCRE_SEL_BY_BUPA';  end
      Fixed_asset = 'FIXED_ASSET'
      def fixed_asset;'FIXED_ASSET';  end
      House_bank = 'HOUSE_BANK'
      def house_bank;'HOUSE_BANK';  end
      Ovh_asses_rule = 'OVH_ASSES_RULE'
      def ovh_asses_rule;'OVH_ASSES_RULE';  end
      Permanent_establishment = 'PERMANENT_ESTABLISHMENT'
      def permanent_establishment;'PERMANENT_ESTABLISHMENT';  end
      Production_lot = 'PRODUCTION_LOT'
      def production_lot;'PRODUCTION_LOT';  end
      Project = 'PROJECT'
      def project;'PROJECT';  end
      Project_task = 'PROJECT_TASK'
      def project_task;'PROJECT_TASK';  end
      Purchase_doc = 'PURCHASE_DOC'
      def purchase_doc;'PURCHASE_DOC';  end
      Purchase_doc_upb = 'PURCHASE_DOC_UPB'
      def purchase_doc_upb;'PURCHASE_DOC_UPB';  end
      Root = 'ROOT'
      def root;'ROOT';  end
      Sales_organisation = 'SALES_ORGANISATION'
      def sales_organisation;'SALES_ORGANISATION';  end
      Sal_ser_doc = 'SAL_SER_DOC'
      def sal_ser_doc;'SAL_SER_DOC';  end
      Sel_by_production_lot = 'SEL_BY_PRODUCTION_LOT'
      def sel_by_production_lot;'SEL_BY_PRODUCTION_LOT';  end
      Set_of_books = 'SET_OF_BOOKS'
      def set_of_books;'SET_OF_BOOKS';  end
   end
   module Co_action
      module_function
      module Root
         module_function
         Compound_schedule = 'COMPOUND_SCHEDULE'
         def compound_schedule;'COMPOUND_SCHEDULE';  end
         CREATE = 'CREATE'
         def CREATE;'CREATE';  end
         Execute = 'EXECUTE'
         def execute;'EXECUTE';  end
      end
   end
   module Co_assoc
      module_function
      module Bupa
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Company
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Cost_centre
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Cust_ser_org
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Fav_cost_object
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Fcre_root
         module_function
         Fcre_sel_by_bupa = 'FCRE_SEL_BY_BUPA'
         def fcre_sel_by_bupa;'FCRE_SEL_BY_BUPA';  end
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Fcre_sel_by_bupa
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Fixed_asset
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module House_bank
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Ovh_asses_rule
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Permanent_establishment
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Production_lot
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Project
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Project_task
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Purchase_doc
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Purchase_doc_upb
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Root
         module_function
         Bupa = 'BUPA'
         def bupa;'BUPA';  end
         Company = 'COMPANY'
         def company;'COMPANY';  end
         Comp_fin_proc_ctrl = 'COMP_FIN_PROC_CTRL'
         def comp_fin_proc_ctrl;'COMP_FIN_PROC_CTRL';  end
         Cost_centre = 'COST_CENTRE'
         def cost_centre;'COST_CENTRE';  end
         Cust_ser_org = 'CUST_SER_ORG'
         def cust_ser_org;'CUST_SER_ORG';  end
         Fav_cost_object = 'FAV_COST_OBJECT'
         def fav_cost_object;'FAV_COST_OBJECT';  end
         Fcre_root = 'FCRE_ROOT'
         def fcre_root;'FCRE_ROOT';  end
         Fixed_asset = 'FIXED_ASSET'
         def fixed_asset;'FIXED_ASSET';  end
         House_bank = 'HOUSE_BANK'
         def house_bank;'HOUSE_BANK';  end
         Ovh_asses_rule = 'OVH_ASSES_RULE'
         def ovh_asses_rule;'OVH_ASSES_RULE';  end
         Permanent_establishment = 'PERMANENT_ESTABLISHMENT'
         def permanent_establishment;'PERMANENT_ESTABLISHMENT';  end
         Production_lot = 'PRODUCTION_LOT'
         def production_lot;'PRODUCTION_LOT';  end
         Project = 'PROJECT'
         def project;'PROJECT';  end
         Project_task = 'PROJECT_TASK'
         def project_task;'PROJECT_TASK';  end
         Purchase_doc = 'PURCHASE_DOC'
         def purchase_doc;'PURCHASE_DOC';  end
         Purchase_doc_upb = 'PURCHASE_DOC_UPB'
         def purchase_doc_upb;'PURCHASE_DOC_UPB';  end
         Sales_organisation = 'SALES_ORGANISATION'
         def sales_organisation;'SALES_ORGANISATION';  end
         Sal_ser_doc = 'SAL_SER_DOC'
         def sal_ser_doc;'SAL_SER_DOC';  end
         Sel_by_production_lot = 'SEL_BY_PRODUCTION_LOT'
         def sel_by_production_lot;'SEL_BY_PRODUCTION_LOT';  end
         Set_of_books = 'SET_OF_BOOKS'
         def set_of_books;'SET_OF_BOOKS';  end
         To_open_task = 'TO_OPEN_TASK'
         def to_open_task;'TO_OPEN_TASK';  end
      end
      module Sales_organisation
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Sal_ser_doc
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Sel_by_production_lot
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
      module Set_of_books
         module_function
         To_parent = 'TO_PARENT'
         def to_parent;'TO_PARENT';  end
         To_root = 'TO_ROOT'
         def to_root;'TO_ROOT';  end
      end
   end
   module Co_query
      module_function
      module Root
         module_function
         Select_all = 'SELECT_ALL'
         def select_all;'SELECT_ALL';  end
      end
   end
   module Co_key
      module_function
      module Root
         module_function
         Production_lot_formatted_id = 'PRODUCTION_LOT_FORMATTED_ID'
         def production_lot_formatted_id;'PRODUCTION_LOT_FORMATTED_ID';  end
      end
   end
   module Co_attr
      module_function
      module Bupa
         module_function
         Formatted_name = 'FORMATTED_NAME'
         def formatted_name;'FORMATTED_NAME';  end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Company
         module_function
         module Name
            module_function
            Content = 'NAME-CONTENT'
            def content;'NAME-CONTENT';  end
            Language_code = 'NAME-LANGUAGE_CODE'
            def language_code;'NAME-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Cost_centre
         module_function
         module Name
            module_function
            Content = 'NAME-CONTENT'
            def content;'NAME-CONTENT';  end
            Language_code = 'NAME-LANGUAGE_CODE'
            def language_code;'NAME-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Cust_ser_org
         module_function
         module Name
            module_function
            Content = 'NAME-CONTENT'
            def content;'NAME-CONTENT';  end
            Language_code = 'NAME-LANGUAGE_CODE'
            def language_code;'NAME-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Fav_cost_object
         module_function
         module Description
            module_function
            Content = 'DESCRIPTION-CONTENT'
            def content;'DESCRIPTION-CONTENT';  end
            Language_code = 'DESCRIPTION-LANGUAGE_CODE'
            def language_code;'DESCRIPTION-LANGUAGE_CODE';  end
         end
         module Key
            module_function
            Cost_object_id = 'KEY-COST_OBJECT_ID'
            def cost_object_id;'KEY-COST_OBJECT_ID';  end
            Cost_object_type_code = 'KEY-COST_OBJECT_TYPE_CODE'
            def cost_object_type_code;'KEY-COST_OBJECT_TYPE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Fcre_root
         module_function
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Fcre_sel_by_bupa
         module_function
         Inclusion_exclusion_code = 'INCLUSION_EXCLUSION_CODE'
         def inclusion_exclusion_code;'INCLUSION_EXCLUSION_CODE';  end
         Interval_boundary_type_code = 'INTERVAL_BOUNDARY_TYPE_CODE'
         def interval_boundary_type_code;'INTERVAL_BOUNDARY_TYPE_CODE';  end
         Lowb_business_partner_frmt_nam = 'LOWB_BUSINESS_PARTNER_FRMT_NAM'
         def lowb_business_partner_frmt_nam;'LOWB_BUSINESS_PARTNER_FRMT_NAM';  end
         Lowb_business_partner_id = 'LOWB_BUSINESS_PARTNER_ID'
         def lowb_business_partner_id;'LOWB_BUSINESS_PARTNER_ID';  end
         module Lowb_business_partner_uuid
            module_function
            Content = 'LOWB_BUSINESS_PARTNER_UUID-CONTENT'
            def content;'LOWB_BUSINESS_PARTNER_UUID-CONTENT';  end
            Scheme_agency_id = 'LOWB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'LOWB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'LOWB_BUSINESS_PARTNER_UUID-SCHEME_ID'
            def scheme_id;'LOWB_BUSINESS_PARTNER_UUID-SCHEME_ID';  end
         end
         Upb_business_partner_frmt_nam = 'UPB_BUSINESS_PARTNER_FRMT_NAM'
         def upb_business_partner_frmt_nam;'UPB_BUSINESS_PARTNER_FRMT_NAM';  end
         Upb_business_partner_id = 'UPB_BUSINESS_PARTNER_ID'
         def upb_business_partner_id;'UPB_BUSINESS_PARTNER_ID';  end
         module Upb_business_partner_uuid
            module_function
            Content = 'UPB_BUSINESS_PARTNER_UUID-CONTENT'
            def content;'UPB_BUSINESS_PARTNER_UUID-CONTENT';  end
            Scheme_agency_id = 'UPB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UPB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UPB_BUSINESS_PARTNER_UUID-SCHEME_ID'
            def scheme_id;'UPB_BUSINESS_PARTNER_UUID-SCHEME_ID';  end
         end
      end
      module Fixed_asset
         module_function
         module Master_fixed_asset_id
            module_function
            Content = 'MASTER_FIXED_ASSET_ID-CONTENT'
            def content;'MASTER_FIXED_ASSET_ID-CONTENT';  end
            Scheme_agency_id = 'MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'MASTER_FIXED_ASSET_ID-SCHEME_ID'
            def scheme_id;'MASTER_FIXED_ASSET_ID-SCHEME_ID';  end
         end
         Master_fixed_asset_name = 'MASTER_FIXED_ASSET_NAME'
         def master_fixed_asset_name;'MASTER_FIXED_ASSET_NAME';  end
         module Master_fixed_asset_uuid
            module_function
            Content = 'MASTER_FIXED_ASSET_UUID-CONTENT'
            def content;'MASTER_FIXED_ASSET_UUID-CONTENT';  end
            Scheme_agency_id = 'MASTER_FIXED_ASSET_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'MASTER_FIXED_ASSET_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'MASTER_FIXED_ASSET_UUID-SCHEME_ID'
            def scheme_id;'MASTER_FIXED_ASSET_UUID-SCHEME_ID';  end
         end
         Name = 'NAME'
         def name;'NAME';  end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module House_bank
         module_function
         Formatted_name = 'FORMATTED_NAME'
         def formatted_name;'FORMATTED_NAME';  end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Ovh_asses_rule
         module_function
         module Description
            module_function
            Content = 'DESCRIPTION-CONTENT'
            def content;'DESCRIPTION-CONTENT';  end
            Language_code = 'DESCRIPTION-LANGUAGE_CODE'
            def language_code;'DESCRIPTION-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Permanent_establishment
         module_function
         module Name
            module_function
            Content = 'NAME-CONTENT'
            def content;'NAME-CONTENT';  end
            Language_code = 'NAME-LANGUAGE_CODE'
            def language_code;'NAME-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Production_lot
         module_function
         module Production_lot
            module_function
            Formatted_id = 'PRODUCTION_LOT-FORMATTED_ID'
            def formatted_id;'PRODUCTION_LOT-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PRODUCTION_LOT-OBJECT_ID-CONTENT'
               def content;'PRODUCTION_LOT-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PRODUCTION_LOT-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PRODUCTION_LOT-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PRODUCTION_LOT-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PRODUCTION_LOT-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PRODUCTION_LOT-OBJECT_TYPE_CODE-CONTENT'
               def content;'PRODUCTION_LOT-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PRODUCTION_LOT-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PRODUCTION_LOT-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PRODUCTION_LOT-UUID-CONTENT'
               def content;'PRODUCTION_LOT-UUID-CONTENT';  end
               Scheme_agency_id = 'PRODUCTION_LOT-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PRODUCTION_LOT-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PRODUCTION_LOT-UUID-SCHEME_ID'
               def scheme_id;'PRODUCTION_LOT-UUID-SCHEME_ID';  end
            end
         end
      end
      module Project
         module_function
         module Base_pro_name
            module_function
            Content = 'BASE_PRO_NAME-CONTENT'
            def content;'BASE_PRO_NAME-CONTENT';  end
            Language_code = 'BASE_PRO_NAME-LANGUAGE_CODE'
            def language_code;'BASE_PRO_NAME-LANGUAGE_CODE';  end
         end
         module Base_pro_uuid
            module_function
            Content = 'BASE_PRO_UUID-CONTENT'
            def content;'BASE_PRO_UUID-CONTENT';  end
            Scheme_agency_id = 'BASE_PRO_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'BASE_PRO_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'BASE_PRO_UUID-SCHEME_ID'
            def scheme_id;'BASE_PRO_UUID-SCHEME_ID';  end
         end
      end
      module Project_task
         module_function
         module Project_task_name
            module_function
            Content = 'PROJECT_TASK_NAME-CONTENT'
            def content;'PROJECT_TASK_NAME-CONTENT';  end
            Language_code = 'PROJECT_TASK_NAME-LANGUAGE_CODE'
            def language_code;'PROJECT_TASK_NAME-LANGUAGE_CODE';  end
         end
         module Project_task_uuid
            module_function
            Content = 'PROJECT_TASK_UUID-CONTENT'
            def content;'PROJECT_TASK_UUID-CONTENT';  end
            Scheme_agency_id = 'PROJECT_TASK_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'PROJECT_TASK_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'PROJECT_TASK_UUID-SCHEME_ID'
            def scheme_id;'PROJECT_TASK_UUID-SCHEME_ID';  end
         end
      end
      module Purchase_doc
         module_function
         module Purchase_doc
            module_function
            Formatted_id = 'PURCHASE_DOC-FORMATTED_ID'
            def formatted_id;'PURCHASE_DOC-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PURCHASE_DOC-OBJECT_ID-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PURCHASE_DOC-UUID-CONTENT'
               def content;'PURCHASE_DOC-UUID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PURCHASE_DOC-UUID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC-UUID-SCHEME_ID';  end
            end
         end
      end
      module Purchase_doc_upb
         module_function
         module Purchase_doc
            module_function
            Formatted_id = 'PURCHASE_DOC-FORMATTED_ID'
            def formatted_id;'PURCHASE_DOC-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PURCHASE_DOC-OBJECT_ID-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PURCHASE_DOC-UUID-CONTENT'
               def content;'PURCHASE_DOC-UUID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PURCHASE_DOC-UUID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC-UUID-SCHEME_ID';  end
            end
         end
      end
      module Root
         module_function
         Accounting_closing_step_code = 'ACCOUNTING_CLOSING_STEP_CODE'
         def accounting_closing_step_code;'ACCOUNTING_CLOSING_STEP_CODE';  end
         Accounting_period_id = 'ACCOUNTING_PERIOD_ID'
         def accounting_period_id;'ACCOUNTING_PERIOD_ID';  end
         module Acl_company_uuid
            module_function
            Content = 'ACL_COMPANY_UUID-CONTENT'
            def content;'ACL_COMPANY_UUID-CONTENT';  end
            Scheme_agency_id = 'ACL_COMPANY_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'ACL_COMPANY_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'ACL_COMPANY_UUID-SCHEME_ID'
            def scheme_id;'ACL_COMPANY_UUID-SCHEME_ID';  end
         end
         Ap_or_ar = 'AP_OR_AR'
         def ap_or_ar;'AP_OR_AR';  end
         Assignment_type = 'ASSIGNMENT_TYPE'
         def assignment_type;'ASSIGNMENT_TYPE';  end
         Bcf_step_code = 'BCF_STEP_CODE'
         def bcf_step_code;'BCF_STEP_CODE';  end
         Business_partner_id = 'BUSINESS_PARTNER_ID'
         def business_partner_id;'BUSINESS_PARTNER_ID';  end
         module Can_mdro_description
            module_function
            Content = 'CAN_MDRO_DESCRIPTION-CONTENT'
            def content;'CAN_MDRO_DESCRIPTION-CONTENT';  end
            Language_code = 'CAN_MDRO_DESCRIPTION-LANGUAGE_CODE'
            def language_code;'CAN_MDRO_DESCRIPTION-LANGUAGE_CODE';  end
         end
         module Can_mdro_id
            module_function
            Content = 'CAN_MDRO_ID-CONTENT'
            def content;'CAN_MDRO_ID-CONTENT';  end
            Scheme_agency_id = 'CAN_MDRO_ID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'CAN_MDRO_ID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'CAN_MDRO_ID-SCHEME_ID'
            def scheme_id;'CAN_MDRO_ID-SCHEME_ID';  end
         end
         module Can_mdro_log_section_uuid
            module_function
            Content = 'CAN_MDRO_LOG_SECTION_UUID-CONTENT'
            def content;'CAN_MDRO_LOG_SECTION_UUID-CONTENT';  end
            Scheme_agency_id = 'CAN_MDRO_LOG_SECTION_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'CAN_MDRO_LOG_SECTION_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'CAN_MDRO_LOG_SECTION_UUID-SCHEME_ID'
            def scheme_id;'CAN_MDRO_LOG_SECTION_UUID-SCHEME_ID';  end
         end
         module Can_mdro_uuid
            module_function
            Content = 'CAN_MDRO_UUID-CONTENT'
            def content;'CAN_MDRO_UUID-CONTENT';  end
            Scheme_agency_id = 'CAN_MDRO_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'CAN_MDRO_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'CAN_MDRO_UUID-SCHEME_ID'
            def scheme_id;'CAN_MDRO_UUID-SCHEME_ID';  end
         end
         Chart_of_accounts_code = 'CHART_OF_ACCOUNTS_CODE'
         def chart_of_accounts_code;'CHART_OF_ACCOUNTS_CODE';  end
         module Chart_of_accounts_item_code
            module_function
            Content = 'CHART_OF_ACCOUNTS_ITEM_CODE-CONTENT'
            def content;'CHART_OF_ACCOUNTS_ITEM_CODE-CONTENT';  end
            List_id = 'CHART_OF_ACCOUNTS_ITEM_CODE-LIST_ID'
            def list_id;'CHART_OF_ACCOUNTS_ITEM_CODE-LIST_ID';  end
         end
         Company_id = 'COMPANY_ID'
         def company_id;'COMPANY_ID';  end
         Correction_run_indicator = 'CORRECTION_RUN_INDICATOR'
         def correction_run_indicator;'CORRECTION_RUN_INDICATOR';  end
         Cost_centre_id = 'COST_CENTRE_ID'
         def cost_centre_id;'COST_CENTRE_ID';  end
         Currency_code = 'CURRENCY_CODE'
         def currency_code;'CURRENCY_CODE';  end
         module Cust_ser_document_id
            module_function
            Formatted_id = 'CUST_SER_DOCUMENT_ID-FORMATTED_ID'
            def formatted_id;'CUST_SER_DOCUMENT_ID-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-CONTENT'
               def content;'CUST_SER_DOCUMENT_ID-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_ID'
               def scheme_id;'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT'
               def content;'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'CUST_SER_DOCUMENT_ID-UUID-CONTENT'
               def content;'CUST_SER_DOCUMENT_ID-UUID-CONTENT';  end
               Scheme_agency_id = 'CUST_SER_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'CUST_SER_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'CUST_SER_DOCUMENT_ID-UUID-SCHEME_ID'
               def scheme_id;'CUST_SER_DOCUMENT_ID-UUID-SCHEME_ID';  end
            end
         end
         module Cust_ser_document_type
            module_function
            Content = 'CUST_SER_DOCUMENT_TYPE-CONTENT'
            def content;'CUST_SER_DOCUMENT_TYPE-CONTENT';  end
            List_id = 'CUST_SER_DOCUMENT_TYPE-LIST_ID'
            def list_id;'CUST_SER_DOCUMENT_TYPE-LIST_ID';  end
         end
         Cust_ser_org_id = 'CUST_SER_ORG_ID'
         def cust_ser_org_id;'CUST_SER_ORG_ID';  end
         module Description
            module_function
            Content = 'DESCRIPTION-CONTENT'
            def content;'DESCRIPTION-CONTENT';  end
            Language_code = 'DESCRIPTION-LANGUAGE_CODE'
            def language_code;'DESCRIPTION-LANGUAGE_CODE';  end
         end
         Direct_material_indicator = 'DIRECT_MATERIAL_INDICATOR'
         def direct_material_indicator;'DIRECT_MATERIAL_INDICATOR';  end
         Enable_diplay_log = 'ENABLE_DIPLAY_LOG'
         def enable_diplay_log;'ENABLE_DIPLAY_LOG';  end
         Fiscal_year_id = 'FISCAL_YEAR_ID'
         def fiscal_year_id;'FISCAL_YEAR_ID';  end
         Fixed_asset_class = 'FIXED_ASSET_CLASS'
         def fixed_asset_class;'FIXED_ASSET_CLASS';  end
         module Fixed_asset_key
            module_function
            module Company_uuid
               module_function
               Content = 'FIXED_ASSET_KEY-COMPANY_UUID-CONTENT'
               def content;'FIXED_ASSET_KEY-COMPANY_UUID-CONTENT';  end
               Scheme_agency_id = 'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_ID'
               def scheme_id;'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_ID';  end
            end
            module Id
               module_function
               Content = 'FIXED_ASSET_KEY-ID-CONTENT'
               def content;'FIXED_ASSET_KEY-ID-CONTENT';  end
               Scheme_agency_id = 'FIXED_ASSET_KEY-ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'FIXED_ASSET_KEY-ID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'FIXED_ASSET_KEY-ID-SCHEME_ID'
               def scheme_id;'FIXED_ASSET_KEY-ID-SCHEME_ID';  end
            end
            module Master_fixed_asset_id
               module_function
               Content = 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-CONTENT'
               def content;'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-CONTENT';  end
               Scheme_agency_id = 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_ID'
               def scheme_id;'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_ID';  end
            end
         end
         Fxasr_type_code = 'FXASR_TYPE_CODE'
         def fxasr_type_code;'FXASR_TYPE_CODE';  end
         House_bank_id = 'HOUSE_BANK_ID'
         def house_bank_id;'HOUSE_BANK_ID';  end
         module Id
            module_function
            Content = 'ID-CONTENT'
            def content;'ID-CONTENT';  end
            Scheme_agency_id = 'ID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'ID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'ID-SCHEME_ID'
            def scheme_id;'ID-SCHEME_ID';  end
         end
         Is_period_end_close_triggered = 'IS_PERIOD_END_CLOSE_TRIGGERED'
         def is_period_end_close_triggered;'IS_PERIOD_END_CLOSE_TRIGGERED';  end
         module Key
            module_function
            Cost_object_id = 'KEY-COST_OBJECT_ID'
            def cost_object_id;'KEY-COST_OBJECT_ID';  end
            Cost_object_type_code = 'KEY-COST_OBJECT_TYPE_CODE'
            def cost_object_type_code;'KEY-COST_OBJECT_TYPE_CODE';  end
         end
         Life_cycle_status = 'LIFE_CYCLE_STATUS'
         def life_cycle_status;'LIFE_CYCLE_STATUS';  end
         module Log_section_uuid
            module_function
            Content = 'LOG_SECTION_UUID-CONTENT'
            def content;'LOG_SECTION_UUID-CONTENT';  end
            Scheme_agency_id = 'LOG_SECTION_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'LOG_SECTION_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'LOG_SECTION_UUID-SCHEME_ID'
            def scheme_id;'LOG_SECTION_UUID-SCHEME_ID';  end
         end
         Mdro_type_code = 'MDRO_TYPE_CODE'
         def mdro_type_code;'MDRO_TYPE_CODE';  end
         Multi_customer_proj_indicator = 'MULTI_CUSTOMER_PROJ_INDICATOR'
         def multi_customer_proj_indicator;'MULTI_CUSTOMER_PROJ_INDICATOR';  end
         Ovh_assess_rule_id = 'OVH_ASSESS_RULE_ID'
         def ovh_assess_rule_id;'OVH_ASSESS_RULE_ID';  end
         Party_role_category_code = 'PARTY_ROLE_CATEGORY_CODE'
         def party_role_category_code;'PARTY_ROLE_CATEGORY_CODE';  end
         Permanent_establishment_id = 'PERMANENT_ESTABLISHMENT_ID'
         def permanent_establishment_id;'PERMANENT_ESTABLISHMENT_ID';  end
         module Processing_status
            module_function
            Processing_status_code = 'PROCESSING_STATUS-PROCESSING_STATUS_CODE'
            def processing_status_code;'PROCESSING_STATUS-PROCESSING_STATUS_CODE';  end
         end
         module Production_lot_formatted_id
            module_function
            Formatted_id = 'PRODUCTION_LOT_FORMATTED_ID-FORMATTED_ID'
            def formatted_id;'PRODUCTION_LOT_FORMATTED_ID-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-CONTENT'
               def content;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-CONTENT'
               def content;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PRODUCTION_LOT_FORMATTED_ID-UUID-CONTENT'
               def content;'PRODUCTION_LOT_FORMATTED_ID-UUID-CONTENT';  end
               Scheme_agency_id = 'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_ID'
               def scheme_id;'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_ID';  end
            end
         end
         Product_type_code = 'PRODUCT_TYPE_CODE'
         def product_type_code;'PRODUCT_TYPE_CODE';  end
         Projection_bo_name = 'PROJECTION_BO_NAME'
         def projection_bo_name;'PROJECTION_BO_NAME';  end
         module Project_id
            module_function
            Content = 'PROJECT_ID-CONTENT'
            def content;'PROJECT_ID-CONTENT';  end
            Scheme_agency_id = 'PROJECT_ID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'PROJECT_ID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'PROJECT_ID-SCHEME_ID'
            def scheme_id;'PROJECT_ID-SCHEME_ID';  end
         end
         Project_task_id = 'PROJECT_TASK_ID'
         def project_task_id;'PROJECT_TASK_ID';  end
         module Purchase_doc_id
            module_function
            Formatted_id = 'PURCHASE_DOC_ID-FORMATTED_ID'
            def formatted_id;'PURCHASE_DOC_ID-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PURCHASE_DOC_ID-OBJECT_ID-CONTENT'
               def content;'PURCHASE_DOC_ID-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PURCHASE_DOC_ID-UUID-CONTENT'
               def content;'PURCHASE_DOC_ID-UUID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC_ID-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC_ID-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PURCHASE_DOC_ID-UUID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC_ID-UUID-SCHEME_ID';  end
            end
         end
         module Purchase_doc_id_upb
            module_function
            Formatted_id = 'PURCHASE_DOC_ID_UPB-FORMATTED_ID'
            def formatted_id;'PURCHASE_DOC_ID_UPB-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-CONTENT'
               def content;'PURCHASE_DOC_ID_UPB-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-CONTENT'
               def content;'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'PURCHASE_DOC_ID_UPB-UUID-CONTENT'
               def content;'PURCHASE_DOC_ID_UPB-UUID-CONTENT';  end
               Scheme_agency_id = 'PURCHASE_DOC_ID_UPB-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'PURCHASE_DOC_ID_UPB-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'PURCHASE_DOC_ID_UPB-UUID-SCHEME_ID'
               def scheme_id;'PURCHASE_DOC_ID_UPB-UUID-SCHEME_ID';  end
            end
         end
         module Purchase_doc_type
            module_function
            Content = 'PURCHASE_DOC_TYPE-CONTENT'
            def content;'PURCHASE_DOC_TYPE-CONTENT';  end
            List_id = 'PURCHASE_DOC_TYPE-LIST_ID'
            def list_id;'PURCHASE_DOC_TYPE-LIST_ID';  end
         end
         module Rac_id
            module_function
            Formatted_id = 'RAC_ID-FORMATTED_ID'
            def formatted_id;'RAC_ID-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'RAC_ID-OBJECT_ID-CONTENT'
               def content;'RAC_ID-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'RAC_ID-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'RAC_ID-OBJECT_ID-SCHEME_ID'
               def scheme_id;'RAC_ID-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'RAC_ID-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'RAC_ID-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'RAC_ID-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'RAC_ID-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'RAC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'RAC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'RAC_ID-OBJECT_TYPE_CODE-CONTENT'
               def content;'RAC_ID-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'RAC_ID-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'RAC_ID-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'RAC_ID-UUID-CONTENT'
               def content;'RAC_ID-UUID-CONTENT';  end
               Scheme_agency_id = 'RAC_ID-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'RAC_ID-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'RAC_ID-UUID-SCHEME_ID'
               def scheme_id;'RAC_ID-UUID-SCHEME_ID';  end
            end
         end
         module Sales_document_id
            module_function
            Formatted_id = 'SALES_DOCUMENT_ID-FORMATTED_ID'
            def formatted_id;'SALES_DOCUMENT_ID-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'SALES_DOCUMENT_ID-OBJECT_ID-CONTENT'
               def content;'SALES_DOCUMENT_ID-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_ID'
               def scheme_id;'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT'
               def content;'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'SALES_DOCUMENT_ID-UUID-CONTENT'
               def content;'SALES_DOCUMENT_ID-UUID-CONTENT';  end
               Scheme_agency_id = 'SALES_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SALES_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'SALES_DOCUMENT_ID-UUID-SCHEME_ID'
               def scheme_id;'SALES_DOCUMENT_ID-UUID-SCHEME_ID';  end
            end
         end
         module Sales_document_type
            module_function
            Content = 'SALES_DOCUMENT_TYPE-CONTENT'
            def content;'SALES_DOCUMENT_TYPE-CONTENT';  end
            List_id = 'SALES_DOCUMENT_TYPE-LIST_ID'
            def list_id;'SALES_DOCUMENT_TYPE-LIST_ID';  end
         end
         Sales_obj_sel_code = 'SALES_OBJ_SEL_CODE'
         def sales_obj_sel_code;'SALES_OBJ_SEL_CODE';  end
         Sales_organisation_id = 'SALES_ORGANISATION_ID'
         def sales_organisation_id;'SALES_ORGANISATION_ID';  end
         module Set_of_books_id
            module_function
            Content = 'SET_OF_BOOKS_ID-CONTENT'
            def content;'SET_OF_BOOKS_ID-CONTENT';  end
            Scheme_agency_id = 'SET_OF_BOOKS_ID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'SET_OF_BOOKS_ID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'SET_OF_BOOKS_ID-SCHEME_ID'
            def scheme_id;'SET_OF_BOOKS_ID-SCHEME_ID';  end
         end
         module Sob_asset_valuation_view_key
            module_function
            module Set_of_books_id
               module_function
               Content = 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-CONTENT'
               def content;'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-CONTENT';  end
               Scheme_agency_id = 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_ID'
               def scheme_id;'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_ID';  end
            end
            module Sob_asset_valuation_view_id
               module_function
               Content = 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-CONTENT'
               def content;'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-CONTENT';  end
               Scheme_agency_id = 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_ID'
               def scheme_id;'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_ID';  end
            end
         end
         Test_run_indicator = 'TEST_RUN_INDICATOR'
         def test_run_indicator;'TEST_RUN_INDICATOR';  end
         Third_party_deal_indicator = 'THIRD_PARTY_DEAL_INDICATOR'
         def third_party_deal_indicator;'THIRD_PARTY_DEAL_INDICATOR';  end
      end
      module Sales_organisation
         module_function
         module Name
            module_function
            Content = 'NAME-CONTENT'
            def content;'NAME-CONTENT';  end
            Language_code = 'NAME-LANGUAGE_CODE'
            def language_code;'NAME-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
      module Sal_ser_doc
         module_function
         module Cust_ret_name
            module_function
            Content = 'CUST_RET_NAME-CONTENT'
            def content;'CUST_RET_NAME-CONTENT';  end
            Language_code = 'CUST_RET_NAME-LANGUAGE_CODE'
            def language_code;'CUST_RET_NAME-LANGUAGE_CODE';  end
         end
         module Sal_ord_name
            module_function
            Content = 'SAL_ORD_NAME-CONTENT'
            def content;'SAL_ORD_NAME-CONTENT';  end
            Language_code = 'SAL_ORD_NAME-LANGUAGE_CODE'
            def language_code;'SAL_ORD_NAME-LANGUAGE_CODE';  end
         end
         module Sal_ser_doc
            module_function
            Formatted_id = 'SAL_SER_DOC-FORMATTED_ID'
            def formatted_id;'SAL_SER_DOC-FORMATTED_ID';  end
            module Object_id
               module_function
               Content = 'SAL_SER_DOC-OBJECT_ID-CONTENT'
               def content;'SAL_SER_DOC-OBJECT_ID-CONTENT';  end
               Scheme_agency_id = 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_agency_id = 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID'
               def scheme_agency_scheme_agency_id;'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID';  end
               Scheme_agency_scheme_id = 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID'
               def scheme_agency_scheme_id;'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID';  end
               Scheme_id = 'SAL_SER_DOC-OBJECT_ID-SCHEME_ID'
               def scheme_id;'SAL_SER_DOC-OBJECT_ID-SCHEME_ID';  end
               Scheme_version_id = 'SAL_SER_DOC-OBJECT_ID-SCHEME_VERSION_ID'
               def scheme_version_id;'SAL_SER_DOC-OBJECT_ID-SCHEME_VERSION_ID';  end
            end
            module Object_node_type_code
               module_function
               Content = 'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-CONTENT'
               def content;'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-CONTENT';  end
               List_id = 'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID'
               def list_id;'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID';  end
            end
            module Object_type_code
               module_function
               Content = 'SAL_SER_DOC-OBJECT_TYPE_CODE-CONTENT'
               def content;'SAL_SER_DOC-OBJECT_TYPE_CODE-CONTENT';  end
               List_id = 'SAL_SER_DOC-OBJECT_TYPE_CODE-LIST_ID'
               def list_id;'SAL_SER_DOC-OBJECT_TYPE_CODE-LIST_ID';  end
            end
            module Uuid
               module_function
               Content = 'SAL_SER_DOC-UUID-CONTENT'
               def content;'SAL_SER_DOC-UUID-CONTENT';  end
               Scheme_agency_id = 'SAL_SER_DOC-UUID-SCHEME_AGENCY_ID'
               def scheme_agency_id;'SAL_SER_DOC-UUID-SCHEME_AGENCY_ID';  end
               Scheme_id = 'SAL_SER_DOC-UUID-SCHEME_ID'
               def scheme_id;'SAL_SER_DOC-UUID-SCHEME_ID';  end
            end
         end
         module Ser_conf_name
            module_function
            Content = 'SER_CONF_NAME-CONTENT'
            def content;'SER_CONF_NAME-CONTENT';  end
            Language_code = 'SER_CONF_NAME-LANGUAGE_CODE'
            def language_code;'SER_CONF_NAME-LANGUAGE_CODE';  end
         end
         module Ser_ord_name
            module_function
            Content = 'SER_ORD_NAME-CONTENT'
            def content;'SER_ORD_NAME-CONTENT';  end
            Language_code = 'SER_ORD_NAME-LANGUAGE_CODE'
            def language_code;'SER_ORD_NAME-LANGUAGE_CODE';  end
         end
      end
      module Sel_by_production_lot
         module_function
         Inclusion_exclusion_code = 'INCLUSION_EXCLUSION_CODE'
         def inclusion_exclusion_code;'INCLUSION_EXCLUSION_CODE';  end
         Interval_boundary_type_code = 'INTERVAL_BOUNDARY_TYPE_CODE'
         def interval_boundary_type_code;'INTERVAL_BOUNDARY_TYPE_CODE';  end
         Lowb_prod_lot_formatted_id = 'LOWB_PROD_LOT_FORMATTED_ID'
         def lowb_prod_lot_formatted_id;'LOWB_PROD_LOT_FORMATTED_ID';  end
         module Lowb_prod_lot_uuid
            module_function
            Content = 'LOWB_PROD_LOT_UUID-CONTENT'
            def content;'LOWB_PROD_LOT_UUID-CONTENT';  end
            Scheme_agency_id = 'LOWB_PROD_LOT_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'LOWB_PROD_LOT_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'LOWB_PROD_LOT_UUID-SCHEME_ID'
            def scheme_id;'LOWB_PROD_LOT_UUID-SCHEME_ID';  end
         end
         Upb_prod_lot_formatted_id = 'UPB_PROD_LOT_FORMATTED_ID'
         def upb_prod_lot_formatted_id;'UPB_PROD_LOT_FORMATTED_ID';  end
         module Upb_prod_lot_uuid
            module_function
            Content = 'UPB_PROD_LOT_UUID-CONTENT'
            def content;'UPB_PROD_LOT_UUID-CONTENT';  end
            Scheme_agency_id = 'UPB_PROD_LOT_UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UPB_PROD_LOT_UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UPB_PROD_LOT_UUID-SCHEME_ID'
            def scheme_id;'UPB_PROD_LOT_UUID-SCHEME_ID';  end
         end
      end
      module Set_of_books
         module_function
         module Description
            module_function
            Content = 'DESCRIPTION-CONTENT'
            def content;'DESCRIPTION-CONTENT';  end
            Language_code = 'DESCRIPTION-LANGUAGE_CODE'
            def language_code;'DESCRIPTION-LANGUAGE_CODE';  end
         end
         module Uuid
            module_function
            Content = 'UUID-CONTENT'
            def content;'UUID-CONTENT';  end
            Scheme_agency_id = 'UUID-SCHEME_AGENCY_ID'
            def scheme_agency_id;'UUID-SCHEME_AGENCY_ID';  end
            Scheme_id = 'UUID-SCHEME_ID'
            def scheme_id;'UUID-SCHEME_ID';  end
         end
      end
   end
   module Co_action_p_attr
      module_function
      module Root
         module_function
         module Compound_schedule
            module_function
            Planned_date_time = 'PLANNED_DATE_TIME'
            def planned_date_time;'PLANNED_DATE_TIME';  end
         end
         module Create
            module_function
            Ap_or_ar = 'AP_OR_AR'
            def ap_or_ar;'AP_OR_AR';  end
            Cancellation_run_indicator = 'CANCELLATION_RUN_INDICATOR'
            def cancellation_run_indicator;'CANCELLATION_RUN_INDICATOR';  end
            Mdro_type_code = 'MDRO_TYPE_CODE'
            def mdro_type_code;'MDRO_TYPE_CODE';  end
            Test_run_indicator = 'TEST_RUN_INDICATOR'
            def test_run_indicator;'TEST_RUN_INDICATOR';  end
         end
      end
   end

end
