# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
module If_bsa_adaptation_handler


   if_bsa_adaptation_handler=If_bsa_adaptation_handler
   module Co_buffering_mode
      module_function
      Unspecified = '?'
      def unspecified;'?';  end
      Buffered = 'B'
      def buffered;'B';  end
      Unbuffered = '-'
      def unbuffered;'-';  end
   end
   include If_esf_types
end
