# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_esf_provider_query

   # methods QUERY
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_QUERY_NAME type STRING
   #       !IN_SELECTION_PARAMETERS type TT_SELECTION_PARAMETERS optional
   #       !IN_QUERY_OPTIONS type TY_QUERY_OPTIONS
   #       !IN_AUTHORIZATION_CONTEXT type TY_AUTHORIZATION_CONTEXT optional
   #       !IN_MESSAGE_HANDLER type ref to IF_ESF_MESSAGE_HANDLER
   #       !IN_FILL_DATA type SESF_BOOLEAN default SPACE
   #       !IN_FILTER_NODE_IDS type SESF_BO_NODE_ID_TAB optional
   #       !IN_REQUESTED_ATTRIBUTES type SESF_STRING_TAB optional
   #       !IN_EXECUTE_OVER_SQL type SESF_BOOLEAN default SPACE
   #     exporting
   #       !OUT_NODE_IDS type SESF_BO_NODE_ID_TAB
   #       !OUT_DATA type INDEX TABLE
   #       !OUT_QUERY_INFO type TY_QUERY_INFO .
   #

   def query(*_a,in_bo_node_name:nil,in_query_name:nil,in_selection_parameters:nil,in_query_options:nil,in_authorization_context:nil,in_message_handler:nil,in_fill_data:nil,in_filter_node_ids:nil,in_requested_attributes:nil,in_execute_over_sql:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods RETRIEVE_DEFAULT_QUERY_PARAM
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_QUERY_NAME type STRING
   #     exporting
   #       !OUT_SELECTION_PARAMETERS type SESF_SELECTION_PARAMETERS_TAB .

   def retrieve_default_query_param(*_a,in_bo_node_name:nil,in_query_name:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end

   module_function
   if_esf_provider_query=If_esf_provider_query

end
