*"* components of interface IF_ESF_PROVIDER_VALUE_SET
interface IF_ESF_PROVIDER_VALUE_SET
  public .


  interface IF_ESF_TYPES load .
  types TY_AUTHORIZATION_CONTEXT type IF_ESF_TYPES=>TY_AUTHORIZATION_CONTEXT .
  types TY_CODE_VALUE type IF_ESF_TYPES=>TY_CODE_VALUE .
  types TT_CODE_VALUES type IF_ESF_TYPES=>TT_CODE_VALUES .

  methods RETRIEVE_CODE_VALUES
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_NODE_ID type SESF_BO_NODE_ID
      !IN_NODE_ID_IS_HANDLE type SESF_BOOLEAN optional
      !IN_ATTRIBUTE_NAME type STRING
      !IN_CONTEXT_PARAMETERS type ANY optional
      !IN_CONTEXT_ATTRIBUTES type SESF_STRING_TAB optional
    exporting
      !OUT_CODE_VALUES type IF_ESF_TYPES=>TT_CODE_VALUES .
  methods RETRIEVE_ACTION_CODE_VALUES
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_ACTION_NAME type STRING
      !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
      !IN_ATTRIBUTE_NAME type STRING
      !IN_CONTEXT_PARAMETERS type ANY optional
      !IN_CONTEXT_ATTRIBUTES type SESF_STRING_TAB optional
    returning
      value(OUT_CODE_VALUES) type IF_ESF_TYPES=>TT_CODE_VALUES .
  methods RETRIEVE_QUERY_CODE_VALUES
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_QUERY_NAME type STRING
      !IN_ATTRIBUTE_NAME type STRING
      !IN_CONTEXT_PARAMETERS type ANY optional
      !IN_CONTEXT_ATTRIBUTES type SESF_STRING_TAB optional
    returning
      value(OUT_CODE_VALUES) type IF_ESF_TYPES=>TT_CODE_VALUES .
  methods RETRIEVE_ACTION_VALUE_SET
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_ACTION_NAME type STRING
      !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
      !IN_ATTRIBUTE_NAME type STRING
      !IN_SELECTION_PARAMETERS type SESF_SELECTION_PARAMETERS_TAB
      !IN_QUERY_OPTIONS type SESF_QUERY_OPTIONS optional
      !IN_AUTHORIZATION_CONTEXT type TY_AUTHORIZATION_CONTEXT optional
    returning
      value(OUT_VALUE_SET_NODE_IDS) type SESF_BO_NODE_ID_TAB .
  methods RETRIEVE_VALUE_SET
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_NODE_ID type SESF_BO_NODE_ID
      !IN_NODE_ID_IS_HANDLE type SESF_BOOLEAN optional
      !IN_ATTRIBUTE_NAME type STRING
      !IN_SELECTION_PARAMETERS type SESF_SELECTION_PARAMETERS_TAB
      !IN_QUERY_OPTIONS type SESF_QUERY_OPTIONS optional
      !IN_AUTHORIZATION_CONTEXT type TY_AUTHORIZATION_CONTEXT optional
    returning
      value(OUT_VALUE_SET_NODE_IDS) type SESF_BO_NODE_ID_TAB .
  methods RETRIEVE_QUERY_VALUE_SET
    importing
      !IN_BO_NODE_NAME type STRING
      !IN_QUERY_NAME type STRING
      !IN_ATTRIBUTE_NAME type STRING
      !IN_SELECTION_PARAMETERS type SESF_SELECTION_PARAMETERS_TAB
      !IN_QUERY_OPTIONS type SESF_QUERY_OPTIONS optional
      !IN_AUTHORIZATION_CONTEXT type TY_AUTHORIZATION_CONTEXT optional
    returning
      value(OUT_VALUE_SET_NODE_IDS) type SESF_BO_NODE_ID_TAB .
endinterface.