# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_esf_provider_transact_ctrl

   # methods ON_AFTER_CHECK_TRANSACTION
   #     importing
   #       !IN_REJECTED type SESF_BOOLEAN
   #     changing
   #       !INOUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .
   #

   def on_after_check_transaction(*_a,in_rejected:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods ON_AFTER_CLEANUP_TRANSACTION
   #     changing
   #       !INOUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .
   #

   def on_after_cleanup_transaction(*_a,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods ON_AFTER_SAVE_TRANSACTION
   #     importing
   #       !IN_REJECTED type SESF_BOOLEAN
   #     changing
   #       !INOUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .
   #

   def on_after_save_transaction(*_a,in_rejected:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods ON_BEFORE_CHECK_TRANSACTION
   #     exporting
   #       !OUT_REJECTED type SESF_BOOLEAN
   #       !OUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .
   #

   def on_before_check_transaction(*_a,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods ON_BEFORE_CLEANUP_TRANSACTION
   #     exporting
   #       !OUT_REJECTED type SESF_BOOLEAN
   #       !OUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .
   #

   def on_before_cleanup_transaction(*_a,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods ON_BEFORE_SAVE_TRANSACTION
   #     exporting
   #       !OUT_REJECTED type SESF_BOOLEAN
   #       !OUT_MESSAGES type CM_ESI_ROOT=>TT_ESI_ROOT .

   def on_before_save_transaction(*_a,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end

   module_function
   if_esf_provider_transact_ctrl=If_esf_provider_transact_ctrl

end
