# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)
require_relative "if_esf_types.rb"

module If_esf_provider_access


   module_function
   if_esf_provider_access=If_esf_provider_access
   include If_esf_types

end
