# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_esf_provider_init


   module_function
   if_esf_provider_init=If_esf_provider_init
   Co_tp_save_and_continue = 0
   def co_tp_save_and_continue;0;  end
   Co_tp_save_and_exit = 1
   def co_tp_save_and_exit;1;  end

end
