# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_esf_types


   module_function
   if_esf_types=If_esf_types
   module Co_context_parameter_names
      module_function
      Application_name = 'APPLICATION_NAME'
      def application_name;'APPLICATION_NAME';  end
      Floorplan_type = 'FLOORPLAN_TYPE'
      def floorplan_type;'FLOORPLAN_TYPE';  end
      Session_hand_over = 'SESSION_HAND_OVER'
      def session_hand_over;'SESSION_HAND_OVER';  end
      Workcenter_name = 'WORKCENTER_NAME'
      def workcenter_name;'WORKCENTER_NAME';  end
   end
   Co_change_mode_create = 'C'
   def co_change_mode_create;'C';  end
   Co_change_mode_delete = 'D'
   def co_change_mode_delete;'D';  end
   Co_change_mode_update = 'U'
   def co_change_mode_update;'U';  end
   Co_check_scope_local = 0
   def co_check_scope_local;0;  end
   Co_check_scope_substructure = 1
   def co_check_scope_substructure;1;  end
   Co_edit = 1
   def co_edit;1;  end
   Co_edit_exclusive = 2
   def co_edit_exclusive;2;  end
   Co_node_id_proxy_name = 'NODE_ID'
   def co_node_id_proxy_name;'NODE_ID';  end
   Co_node_id_esr_name = 'NodeID'
   def co_node_id_esr_name;'NodeID';  end
   Co_parent_node_id_proxy_name = 'PARENT_NODE_ID'
   def co_parent_node_id_proxy_name;'PARENT_NODE_ID';  end
   Co_parent_node_id_esr_name = 'ParentNodeID'
   def co_parent_node_id_esr_name;'ParentNodeID';  end
   Co_root_node_id_proxy_name = 'ROOT_NODE_ID'
   def co_root_node_id_proxy_name;'ROOT_NODE_ID';  end
   Co_root_node_id_esr_name = 'RootNodeID'
   def co_root_node_id_esr_name;'RootNodeID';  end
   module Co_property_change_scope
      module_function
      Type_node = abap_true
      def type_node;abap_true;  end
      Type_association = abap_true
      def type_association;abap_true;  end
      Type_attribute = abap_true
      def type_attribute;abap_true;  end
      Type_action = abap_true
      def type_action;abap_true;  end
   end
   module Co_property_scope_default
      module_function
      All_node_props_requested = 'X'
      def all_node_props_requested;'X';  end
      All_action_props_requested = 'X'
      def all_action_props_requested;'X';  end
      Requested_actions =
      def requested_actions;;  end
      All_association_props_requestd = 'X'
      def all_association_props_requestd;'X';  end
      Requested_associations =
      def requested_associations;;  end
      All_attribute_props_requested = 'X'
      def all_attribute_props_requested;'X';  end
      Requested_attributes =
      def requested_attributes;;  end
   end
   Co_read_only = 0
   def co_read_only;0;  end
   Co_scope_local = 0
   def co_scope_local;0;  end
   Co_scope_substructure = 1
   def co_scope_substructure;1;  end
   Co_image_before_modify = 3
   def co_image_before_modify;3;  end
   Co_image_transactional_buffer = 0
   def co_image_transactional_buffer;0;  end
   Co_image_before_changes = 1
   def co_image_before_changes;1;  end
   Co_image_persistency = 2
   def co_image_persistency;2;  end
   Co_image_current_data = 2
   def co_image_current_data;2;  end
   Co_image_comp_tbuf_vs_db = 0
   def co_image_comp_tbuf_vs_db;0;  end
   Co_image_comp_tbuf_vs_befmod = 1
   def co_image_comp_tbuf_vs_befmod;1;  end
   Co_select_option_equal = 'EQ'
   def co_select_option_equal;'EQ';  end
   Co_select_option_not_equal = 'NE'
   def co_select_option_not_equal;'NE';  end
   Co_select_option_between = 'BT'
   def co_select_option_between;'BT';  end
   Co_select_option_not_between = 'NB'
   def co_select_option_not_between;'NB';  end
   Co_select_option_not_cont_ptrn = 'NP'
   def co_select_option_not_cont_ptrn;'NP';  end
   Co_select_option_contains_ptrn = 'CP'
   def co_select_option_contains_ptrn;'CP';  end
   Co_select_option_greater_equal = 'GE'
   def co_select_option_greater_equal;'GE';  end
   Co_select_option_greater = 'GT'
   def co_select_option_greater;'GT';  end
   Co_select_option_less_equal = 'LE'
   def co_select_option_less_equal;'LE';  end
   Co_select_option_less = 'LT'
   def co_select_option_less;'LT';  end
   Co_select_option_including = 'I'
   def co_select_option_including;'I';  end
   Co_select_option_excluding = 'E'
   def co_select_option_excluding;'E';  end
   Co_phase_finalize = 'PHASE_ON_FINALIZE'
   def co_phase_finalize;'PHASE_ON_FINALIZE';  end
   Co_phase_check_before_save = 'PHASE_ON_CHECK_BEFORE_SAVE'
   def co_phase_check_before_save;'PHASE_ON_CHECK_BEFORE_SAVE';  end
   Co_phase_before_save_event = 'PHASE_ON_BEFORE_SAVE_EVENT'
   def co_phase_before_save_event;'PHASE_ON_BEFORE_SAVE_EVENT';  end
   Co_phase_save = 'PHASE_ON_DO_SAVE'
   def co_phase_save;'PHASE_ON_DO_SAVE';  end
   Co_phase_after_save_event = 'PHASE_ON_AFTER_SAVE_EVENT'
   def co_phase_after_save_event;'PHASE_ON_AFTER_SAVE_EVENT';  end
   Co_phase_after_commit = 'PHASE_ON_AFTER_COMMIT'
   def co_phase_after_commit;'PHASE_ON_AFTER_COMMIT';  end
   Co_phase_after_rejected_save = 'PHASE_ON_AFTER_FAILED_SAVE'
   def co_phase_after_rejected_save;'PHASE_ON_AFTER_FAILED_SAVE';  end
   Co_phase_not_in_save = 'NOT_IN_SAVE_CYCLE'
   def co_phase_not_in_save;'NOT_IN_SAVE_CYCLE';  end
   Co_maximum_rows_unrestricted = - 1
   def co_maximum_rows_unrestricted;- 1;  end
   module Co_association
      module_function
      To_root = 'TO_ROOT'
      def to_root;'TO_ROOT';  end
      To_parent = 'TO_PARENT'
      def to_parent;'TO_PARENT';  end
   end
   Co_oc_in_ovs_phase = 'IN_OVS_PHASE'
   def co_oc_in_ovs_phase;'IN_OVS_PHASE';  end
   Co_oc_no_interaction_since_lc = 'NO_BACKEND_INTERACTION_SINCE_LAST_CALL'
   def co_oc_no_interaction_since_lc;'NO_BACKEND_INTERACTION_SINCE_LAST_CALL';  end
   Co_oc_skipped_failed_creates = 'SAVE_SKIPPED_DUE_TO_FAILED_CREATES'
   def co_oc_skipped_failed_creates;'SAVE_SKIPPED_DUE_TO_FAILED_CREATES';  end
   Co_null_time = '      '
   def co_null_time;'      ';  end
   module Co_interaction_pattern
      module_function
      Save_and_continue = 0
      def save_and_continue;0;  end
      Save_and_exit = 1
      def save_and_exit;1;  end
   end
   Co_save_and_continue_session = 0
   def co_save_and_continue_session;0;  end
   Co_save_and_exit_session = 1
   def co_save_and_exit_session;1;  end
   Co_save_and_continue_at_save = 2
   def co_save_and_continue_at_save;2;  end
   Co_save_and_exit_at_save = 3
   def co_save_and_exit_at_save;3;  end
   Co_buffer_change = 0
   def co_buffer_change;0;  end
   Co_property_change = 1
   def co_property_change;1;  end
   module Co_save_decoupling
      module_function
      None = 0
      def none;0;  end
      Request_phase_1 = 1
      def request_phase_1;1;  end
      Request_phase_2 = 2
      def request_phase_2;2;  end
   end
   Co_do_prefix_separator = '.'
   def co_do_prefix_separator;'.';  end
   Co_do_prefix_abap_separator = '^'
   def co_do_prefix_abap_separator;'^';  end
   module Co_search_execution_mode
      module_function
      Default = 0
      def default;0;  end
      Trexviadbsl = 1
      def trexviadbsl;1;  end
      Hybrid = 2
      def hybrid;2;  end
   end

end
