# Generated by Abap2Ruby(https://github.com/jackieju/abap2ruby)

module If_esf_provider_action

   # methods EXECUTE_ACTION
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_ACTION_NAME type STRING
   #       !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
   #       !IN_ACTION_PARAMETERS type ANY
   #       !IN_REFERENCING_NODE_ELEMENTS type SESF_BO_NODE_REFERENCE_T optional
   #       !IN_CHANGE_HANDLER type ref to IF_ESF_CHANGE_HANDLER
   #       !IN_MESSAGE_HANDLER type ref to IF_ESF_MESSAGE_HANDLER .
   #

   def execute_action(*_a,in_bo_node_name:nil,in_action_name:nil,in_node_ids:nil,in_action_parameters:nil,in_referencing_node_elements:nil,in_change_handler:nil,in_message_handler:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end
   # methods RETRIEVE_DEFAULT_ACTION_PARAM
   #     importing
   #       !IN_BO_NODE_NAME type STRING
   #       !IN_ACTION_NAME type STRING
   #       !IN_NODE_IDS type SESF_BO_NODE_ID_TAB
   #     exporting
   #       !OUT_ACTION_PARAMETERS type ANY .

   def retrieve_default_action_param(*_a,in_bo_node_name:nil,in_action_name:nil,in_node_ids:nil,_i:nil,_e:nil,_b:nil)


      raise "Not implemented"

   end

   module_function
   if_esf_provider_action=If_esf_provider_action

end
