*"* components of interface IF_SAMPLE
interface IF_SAMPLE
  public .


  interfaces IF_ESF_PROVIDER_ACCESS .
  interfaces IF_ESF_PROVIDER_ACTION .
  interfaces IF_ESF_PROVIDER_INIT .
  interfaces IF_ESF_PROVIDER_INTERACT_CTRL .
  interfaces IF_ESF_PROVIDER_QUERY .
  interfaces IF_ESF_PROVIDER_TRANSACT_CTRL .
  interfaces IF_ESF_PROVIDER_VALUE_SET .

  types:
    begin of TY_FCRE_SEL_BY_BUPA,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIA_AAR_CREATE_QAF_EC_002_EL as NODE_ELEMENTS.
    types: end of TY_FCRE_SEL_BY_BUPA .
  types:
    TT_FCRE_SEL_BY_BUPA type standard table of TY_FCRE_SEL_BY_BUPA with default key .
  types:
    begin of TY_PROJECT_TASK,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_PROJECT_TASK_EL as NODE_ELEMENTS.
    types: end of TY_PROJECT_TASK .
  types:
    TT_PROJECT_TASK type standard table of TY_PROJECT_TASK with default key .
  types:
    begin of TY_FAV_COST_OBJECT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_FAV_COST_OBJECT_RS as NODE_ELEMENTS.
    types: end of TY_FAV_COST_OBJECT .
  types:
    TT_FAV_COST_OBJECT type standard table of TY_FAV_COST_OBJECT with default key .
  types:
    begin of TY_PRODUCTION_LOT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_PROD_LOT_EL as NODE_ELEMENTS.
    types: end of TY_PRODUCTION_LOT .
  types:
    TT_PRODUCTION_LOT type standard table of TY_PRODUCTION_LOT with default key .
  types:
    begin of TY_ROOT,
      NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AAR_CREATE_QAF_ECO_EL as NODE_ELEMENTS.
    types: end of TY_ROOT .
  types:
    TT_ROOT type standard table of TY_ROOT with default key .
  types:
    begin of TY_COMPANY,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_ORGCTR_EL as NODE_ELEMENTS.
    types: end of TY_COMPANY .
  types:
    TT_COMPANY type standard table of TY_COMPANY with default key .
  types:
    begin of TY_SET_OF_BOOKS,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_SOB_EL as NODE_ELEMENTS.
    types: end of TY_SET_OF_BOOKS .
  types:
    TT_SET_OF_BOOKS type standard table of TY_SET_OF_BOOKS with default key .
  types:
    begin of TY_BUPA,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_BUPA_EL as NODE_ELEMENTS.
    types: end of TY_BUPA .
  types:
    TT_BUPA type standard table of TY_BUPA with default key .
  types:
    begin of TY_COST_CENTRE,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_ORGCTR_EL as NODE_ELEMENTS.
    types: end of TY_COST_CENTRE .
  types:
    TT_COST_CENTRE type standard table of TY_COST_CENTRE with default key .
  types:
    begin of TY_CUST_SER_ORG,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_ORGCTR_EL as NODE_ELEMENTS.
    types: end of TY_CUST_SER_ORG .
  types:
    TT_CUST_SER_ORG type standard table of TY_CUST_SER_ORG with default key .
  types:
    begin of TY_FIXED_ASSET,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_FIXED_ASSET as NODE_ELEMENTS.
    types: end of TY_FIXED_ASSET .
  types:
    TT_FIXED_ASSET type standard table of TY_FIXED_ASSET with default key .
  types:
    begin of TY_SALES_ORGANISATION,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_ORGCTR_EL as NODE_ELEMENTS.
    types: end of TY_SALES_ORGANISATION .
  types:
    TT_SALES_ORGANISATION type standard table of TY_SALES_ORGANISATION with default key .
  types:
    begin of TY_PROJECT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_PROJECT_EL as NODE_ELEMENTS.
    types: end of TY_PROJECT .
  types:
    TT_PROJECT type standard table of TY_PROJECT with default key .
  types:
    begin of TY_PERMANENT_ESTABLISHMENT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_ORGCTR_EL as NODE_ELEMENTS.
    types: end of TY_PERMANENT_ESTABLISHMENT .
  types:
    TT_PERMANENT_ESTABLISHMENT type standard table of TY_PERMANENT_ESTABLISHMENT with default key .
  types:
    begin of TY_OVH_ASSES_RULE,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_OH_ASSES_RULE_EL as NODE_ELEMENTS.
    types: end of TY_OVH_ASSES_RULE .
  types:
    TT_OVH_ASSES_RULE type standard table of TY_OVH_ASSES_RULE with default key .
  types:
    begin of TY_HOUSE_BANK,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_BUPA_EL as NODE_ELEMENTS.
    types: end of TY_HOUSE_BANK .
  types:
    TT_HOUSE_BANK type standard table of TY_HOUSE_BANK with default key .
  types:
    begin of TY_SAL_SER_DOC,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_SAL_SER_DOC_EL as NODE_ELEMENTS.
    types: end of TY_SAL_SER_DOC .
  types:
    TT_SAL_SER_DOC type standard table of TY_SAL_SER_DOC with default key .
  types:
    begin of TY_PURCHASE_DOC,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIAS_AARC_PUR_DOC_EL as NODE_ELEMENTS.
    types: end of TY_PURCHASE_DOC .
  types:
    TT_PURCHASE_DOC type standard table of TY_PURCHASE_DOC with default key .
  types:
    begin of TY_PURCHASE_DOC_UPB,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIA_AAR_CREATE_QAF_EC_001_EL as NODE_ELEMENTS.
    types: end of TY_PURCHASE_DOC_UPB .
  types:
    TT_PURCHASE_DOC_UPB type standard table of TY_PURCHASE_DOC_UPB with default key .
  types:
    begin of TY_FCRE_ROOT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIA_AAR_CREATE_QAF_EC_003_EL as NODE_ELEMENTS.
    types: end of TY_FCRE_ROOT .
  types:
    TT_FCRE_ROOT type standard table of TY_FCRE_ROOT with default key .
  types:
    begin of TY_SEL_BY_PRODUCTION_LOT,
      NODE_ID type SESF_BO_NODE_ID,
      PARENT_NODE_ID type SESF_BO_NODE_ID.
      include type A1FIA_AAR_CREATE_QAF_EC_004_EL as NODE_ELEMENTS.
    types: end of TY_SEL_BY_PRODUCTION_LOT .
  types:
    TT_SEL_BY_PRODUCTION_LOT type standard table of TY_SEL_BY_PRODUCTION_LOT with default key .
  types:
    begin of TY_ACTION_P,
      begin of ROOT,
        COMPOUND_SCHEDULE              type A1FIA_RUN_SCHEDULE_DIRECTLY_AC,
        CREATE                         type A1FIAS_AARC_CREATE            ,
      end of ROOT,
    end of TY_ACTION_P .
  types:
    begin of TY_KEY,
      begin of ROOT,
        PRODUCTION_LOT_FORMATTED_ID    type A1FIAS_AAR_CREATE_QAF_ECO_EL-PRODUCTION_LOT_FORMATTED_ID,
      end of ROOT,
    end of TY_KEY .
  types:
    begin of TT_KEY,
      begin of ROOT,
        PRODUCTION_LOT_FORMATTED_ID    type standard table of A1FIAS_AAR_CREATE_QAF_ECO_EL-PRODUCTION_LOT_FORMATTED_ID with default key,
      end of ROOT,
    end of TT_KEY .

  constants CO_BO_NAME type STRING value 'Test_bo_name_hello' ##no_text .
  constants:
    begin of CO_BO_NODE,
      BUPA                           type STRING value 'BUPA',
      COMPANY                        type STRING value 'COMPANY',
      COST_CENTRE                    type STRING value 'COST_CENTRE',
      CUST_SER_ORG                   type STRING value 'CUST_SER_ORG',
      FAV_COST_OBJECT                type STRING value 'FAV_COST_OBJECT',
      FCRE_ROOT                      type STRING value 'FCRE_ROOT',
      FCRE_SEL_BY_BUPA               type STRING value 'FCRE_SEL_BY_BUPA',
      FIXED_ASSET                    type STRING value 'FIXED_ASSET',
      HOUSE_BANK                     type STRING value 'HOUSE_BANK',
      OVH_ASSES_RULE                 type STRING value 'OVH_ASSES_RULE',
      PERMANENT_ESTABLISHMENT        type STRING value 'PERMANENT_ESTABLISHMENT',
      PRODUCTION_LOT                 type STRING value 'PRODUCTION_LOT',
      PROJECT                        type STRING value 'PROJECT',
      PROJECT_TASK                   type STRING value 'PROJECT_TASK',
      PURCHASE_DOC                   type STRING value 'PURCHASE_DOC',
      PURCHASE_DOC_UPB               type STRING value 'PURCHASE_DOC_UPB',
      ROOT                           type STRING value 'ROOT',
      SALES_ORGANISATION             type STRING value 'SALES_ORGANISATION',
      SAL_SER_DOC                    type STRING value 'SAL_SER_DOC',
      SEL_BY_PRODUCTION_LOT          type STRING value 'SEL_BY_PRODUCTION_LOT',
      SET_OF_BOOKS                   type STRING value 'SET_OF_BOOKS',
    end of CO_BO_NODE .
  constants:
    begin of CO_ACTION,
      begin of ROOT,
        COMPOUND_SCHEDULE              type STRING value 'COMPOUND_SCHEDULE',
        CREATE                         type STRING value 'CREATE',
        EXECUTE                        type STRING value 'EXECUTE',
      end of ROOT,
    end of CO_ACTION .
  constants:
    begin of CO_ASSOC,
      begin of BUPA,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of BUPA,
      begin of COMPANY,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of COMPANY,
      begin of COST_CENTRE,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of COST_CENTRE,
      begin of CUST_SER_ORG,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of CUST_SER_ORG,
      begin of FAV_COST_OBJECT,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of FAV_COST_OBJECT,
      begin of FCRE_ROOT,
        FCRE_SEL_BY_BUPA               type STRING value 'FCRE_SEL_BY_BUPA',
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of FCRE_ROOT,
      begin of FCRE_SEL_BY_BUPA,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of FCRE_SEL_BY_BUPA,
      begin of FIXED_ASSET,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of FIXED_ASSET,
      begin of HOUSE_BANK,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of HOUSE_BANK,
      begin of OVH_ASSES_RULE,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of OVH_ASSES_RULE,
      begin of PERMANENT_ESTABLISHMENT,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PERMANENT_ESTABLISHMENT,
      begin of PRODUCTION_LOT,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PRODUCTION_LOT,
      begin of PROJECT,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PROJECT,
      begin of PROJECT_TASK,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PROJECT_TASK,
      begin of PURCHASE_DOC,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PURCHASE_DOC,
      begin of PURCHASE_DOC_UPB,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of PURCHASE_DOC_UPB,
      begin of ROOT,
        BUPA                           type STRING value 'BUPA',
        COMPANY                        type STRING value 'COMPANY',
        COMP_FIN_PROC_CTRL             type STRING value 'COMP_FIN_PROC_CTRL',
        COST_CENTRE                    type STRING value 'COST_CENTRE',
        CUST_SER_ORG                   type STRING value 'CUST_SER_ORG',
        FAV_COST_OBJECT                type STRING value 'FAV_COST_OBJECT',
        FCRE_ROOT                      type STRING value 'FCRE_ROOT',
        FIXED_ASSET                    type STRING value 'FIXED_ASSET',
        HOUSE_BANK                     type STRING value 'HOUSE_BANK',
        OVH_ASSES_RULE                 type STRING value 'OVH_ASSES_RULE',
        PERMANENT_ESTABLISHMENT        type STRING value 'PERMANENT_ESTABLISHMENT',
        PRODUCTION_LOT                 type STRING value 'PRODUCTION_LOT',
        PROJECT                        type STRING value 'PROJECT',
        PROJECT_TASK                   type STRING value 'PROJECT_TASK',
        PURCHASE_DOC                   type STRING value 'PURCHASE_DOC',
        PURCHASE_DOC_UPB               type STRING value 'PURCHASE_DOC_UPB',
        SALES_ORGANISATION             type STRING value 'SALES_ORGANISATION',
        SAL_SER_DOC                    type STRING value 'SAL_SER_DOC',
        SEL_BY_PRODUCTION_LOT          type STRING value 'SEL_BY_PRODUCTION_LOT',
        SET_OF_BOOKS                   type STRING value 'SET_OF_BOOKS',
        TO_OPEN_TASK                   type STRING value 'TO_OPEN_TASK',
      end of ROOT,
      begin of SALES_ORGANISATION,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of SALES_ORGANISATION,
      begin of SAL_SER_DOC,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of SAL_SER_DOC,
      begin of SEL_BY_PRODUCTION_LOT,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of SEL_BY_PRODUCTION_LOT,
      begin of SET_OF_BOOKS,
        TO_PARENT                      type STRING value 'TO_PARENT',
        TO_ROOT                        type STRING value 'TO_ROOT',
      end of SET_OF_BOOKS,
    end of CO_ASSOC .
  constants:
    begin of CO_QUERY,
      begin of ROOT,
        SELECT_ALL                     type STRING value 'SELECT_ALL',
      end of ROOT,
    end of CO_QUERY .
  constants:
        begin of CO_KEY,
      begin of ROOT,
        PRODUCTION_LOT_FORMATTED_ID    type STRING value 'PRODUCTION_LOT_FORMATTED_ID',
      end of ROOT,
    end of CO_KEY .
  constants:
    BEGIN OF co_attr,
      BEGIN OF bupa,
        formatted_name                 TYPE string VALUE 'FORMATTED_NAME',
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF bupa,
      BEGIN OF company,
        BEGIN OF name,
          content                        TYPE string VALUE 'NAME-CONTENT',
          language_code                  TYPE string VALUE 'NAME-LANGUAGE_CODE',
        END OF name,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF company,
      BEGIN OF cost_centre,
        BEGIN OF name,
          content                        TYPE string VALUE 'NAME-CONTENT',
          language_code                  TYPE string VALUE 'NAME-LANGUAGE_CODE',
        END OF name,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF cost_centre,
      BEGIN OF cust_ser_org,
        BEGIN OF name,
          content                        TYPE string VALUE 'NAME-CONTENT',
          language_code                  TYPE string VALUE 'NAME-LANGUAGE_CODE',
        END OF name,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF cust_ser_org,
      BEGIN OF fav_cost_object,
        BEGIN OF description,
          content                        TYPE string VALUE 'DESCRIPTION-CONTENT',
          language_code                  TYPE string VALUE 'DESCRIPTION-LANGUAGE_CODE',
        END OF description,
        BEGIN OF key,
          cost_object_id                 TYPE string VALUE 'KEY-COST_OBJECT_ID',
          cost_object_type_code          TYPE string VALUE 'KEY-COST_OBJECT_TYPE_CODE',
        END OF key,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF fav_cost_object,
      BEGIN OF fcre_root,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF fcre_root,
      BEGIN OF fcre_sel_by_bupa,
        inclusion_exclusion_code       TYPE string VALUE 'INCLUSION_EXCLUSION_CODE',
        interval_boundary_type_code    TYPE string VALUE 'INTERVAL_BOUNDARY_TYPE_CODE',
        lowb_business_partner_frmt_nam TYPE string VALUE 'LOWB_BUSINESS_PARTNER_FRMT_NAM',
        lowb_business_partner_id       TYPE string VALUE 'LOWB_BUSINESS_PARTNER_ID',
        BEGIN OF lowb_business_partner_uuid,
          content                        TYPE string VALUE 'LOWB_BUSINESS_PARTNER_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'LOWB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'LOWB_BUSINESS_PARTNER_UUID-SCHEME_ID',
        END OF lowb_business_partner_uuid,
        upb_business_partner_frmt_nam  TYPE string VALUE 'UPB_BUSINESS_PARTNER_FRMT_NAM',
        upb_business_partner_id        TYPE string VALUE 'UPB_BUSINESS_PARTNER_ID',
        BEGIN OF upb_business_partner_uuid,
          content                        TYPE string VALUE 'UPB_BUSINESS_PARTNER_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UPB_BUSINESS_PARTNER_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UPB_BUSINESS_PARTNER_UUID-SCHEME_ID',
        END OF upb_business_partner_uuid,
      END OF fcre_sel_by_bupa,
      BEGIN OF fixed_asset,
        BEGIN OF master_fixed_asset_id,
          content                        TYPE string VALUE 'MASTER_FIXED_ASSET_ID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'MASTER_FIXED_ASSET_ID-SCHEME_ID',
        END OF master_fixed_asset_id,
        master_fixed_asset_name        TYPE string VALUE 'MASTER_FIXED_ASSET_NAME',
        BEGIN OF master_fixed_asset_uuid,
          content                        TYPE string VALUE 'MASTER_FIXED_ASSET_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'MASTER_FIXED_ASSET_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'MASTER_FIXED_ASSET_UUID-SCHEME_ID',
        END OF master_fixed_asset_uuid,
        name                           TYPE string VALUE 'NAME',
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF fixed_asset,
      BEGIN OF house_bank,
        formatted_name                 TYPE string VALUE 'FORMATTED_NAME',
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF house_bank,
      BEGIN OF ovh_asses_rule,
        BEGIN OF description,
          content                        TYPE string VALUE 'DESCRIPTION-CONTENT',
          language_code                  TYPE string VALUE 'DESCRIPTION-LANGUAGE_CODE',
        END OF description,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF ovh_asses_rule,
      BEGIN OF permanent_establishment,
        BEGIN OF name,
          content                        TYPE string VALUE 'NAME-CONTENT',
          language_code                  TYPE string VALUE 'NAME-LANGUAGE_CODE',
        END OF name,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF permanent_establishment,
      BEGIN OF production_lot,
        BEGIN OF production_lot,
          formatted_id                   TYPE string VALUE 'PRODUCTION_LOT-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PRODUCTION_LOT-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PRODUCTION_LOT-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PRODUCTION_LOT-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PRODUCTION_LOT-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PRODUCTION_LOT-UUID-SCHEME_ID',
          END OF uuid,
        END OF production_lot,
      END OF production_lot,
      BEGIN OF project,
        BEGIN OF base_pro_name,
          content                        TYPE string VALUE 'BASE_PRO_NAME-CONTENT',
          language_code                  TYPE string VALUE 'BASE_PRO_NAME-LANGUAGE_CODE',
        END OF base_pro_name,
        BEGIN OF base_pro_uuid,
          content                        TYPE string VALUE 'BASE_PRO_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'BASE_PRO_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'BASE_PRO_UUID-SCHEME_ID',
        END OF base_pro_uuid,
      END OF project,
      BEGIN OF project_task,
        BEGIN OF project_task_name,
          content                        TYPE string VALUE 'PROJECT_TASK_NAME-CONTENT',
          language_code                  TYPE string VALUE 'PROJECT_TASK_NAME-LANGUAGE_CODE',
        END OF project_task_name,
        BEGIN OF project_task_uuid,
          content                        TYPE string VALUE 'PROJECT_TASK_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'PROJECT_TASK_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'PROJECT_TASK_UUID-SCHEME_ID',
        END OF project_task_uuid,
      END OF project_task,
      BEGIN OF purchase_doc,
        BEGIN OF purchase_doc,
          formatted_id                   TYPE string VALUE 'PURCHASE_DOC-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PURCHASE_DOC-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC-UUID-SCHEME_ID',
          END OF uuid,
        END OF purchase_doc,
      END OF purchase_doc,
      BEGIN OF purchase_doc_upb,
        BEGIN OF purchase_doc,
          formatted_id                   TYPE string VALUE 'PURCHASE_DOC-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PURCHASE_DOC-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PURCHASE_DOC-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC-UUID-SCHEME_ID',
          END OF uuid,
        END OF purchase_doc,
      END OF purchase_doc_upb,
      BEGIN OF root,
        accounting_closing_step_code   TYPE string VALUE 'ACCOUNTING_CLOSING_STEP_CODE',
        accounting_period_id           TYPE string VALUE 'ACCOUNTING_PERIOD_ID',
        BEGIN OF acl_company_uuid,
          content                        TYPE string VALUE 'ACL_COMPANY_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'ACL_COMPANY_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'ACL_COMPANY_UUID-SCHEME_ID',
        END OF acl_company_uuid,
        ap_or_ar                       TYPE string VALUE 'AP_OR_AR',
        assignment_type                TYPE string VALUE 'ASSIGNMENT_TYPE',
        bcf_step_code                  TYPE string VALUE 'BCF_STEP_CODE',
        business_partner_id            TYPE string VALUE 'BUSINESS_PARTNER_ID',
        BEGIN OF can_mdro_description,
          content                        TYPE string VALUE 'CAN_MDRO_DESCRIPTION-CONTENT',
          language_code                  TYPE string VALUE 'CAN_MDRO_DESCRIPTION-LANGUAGE_CODE',
        END OF can_mdro_description,
        BEGIN OF can_mdro_id,
          content                        TYPE string VALUE 'CAN_MDRO_ID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'CAN_MDRO_ID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'CAN_MDRO_ID-SCHEME_ID',
        END OF can_mdro_id,
        BEGIN OF can_mdro_log_section_uuid,
          content                        TYPE string VALUE 'CAN_MDRO_LOG_SECTION_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'CAN_MDRO_LOG_SECTION_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'CAN_MDRO_LOG_SECTION_UUID-SCHEME_ID',
        END OF can_mdro_log_section_uuid,
        BEGIN OF can_mdro_uuid,
          content                        TYPE string VALUE 'CAN_MDRO_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'CAN_MDRO_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'CAN_MDRO_UUID-SCHEME_ID',
        END OF can_mdro_uuid,
        chart_of_accounts_code         TYPE string VALUE 'CHART_OF_ACCOUNTS_CODE',
        BEGIN OF chart_of_accounts_item_code,
          content                        TYPE string VALUE 'CHART_OF_ACCOUNTS_ITEM_CODE-CONTENT',
          list_id                        TYPE string VALUE 'CHART_OF_ACCOUNTS_ITEM_CODE-LIST_ID',
        END OF chart_of_accounts_item_code,
        company_id                     TYPE string VALUE 'COMPANY_ID',
        correction_run_indicator       TYPE string VALUE 'CORRECTION_RUN_INDICATOR',
        cost_centre_id                 TYPE string VALUE 'COST_CENTRE_ID',
        currency_code                  TYPE string VALUE 'CURRENCY_CODE',
        BEGIN OF cust_ser_document_id,
          formatted_id                   TYPE string VALUE 'CUST_SER_DOCUMENT_ID-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'CUST_SER_DOCUMENT_ID-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'CUST_SER_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'CUST_SER_DOCUMENT_ID-UUID-SCHEME_ID',
          END OF uuid,
        END OF cust_ser_document_id,
        BEGIN OF cust_ser_document_type,
          content                        TYPE string VALUE 'CUST_SER_DOCUMENT_TYPE-CONTENT',
          list_id                        TYPE string VALUE 'CUST_SER_DOCUMENT_TYPE-LIST_ID',
        END OF cust_ser_document_type,
        cust_ser_org_id                TYPE string VALUE 'CUST_SER_ORG_ID',
        BEGIN OF description,
          content                        TYPE string VALUE 'DESCRIPTION-CONTENT',
          language_code                  TYPE string VALUE 'DESCRIPTION-LANGUAGE_CODE',
        END OF description,
        direct_material_indicator      TYPE string VALUE 'DIRECT_MATERIAL_INDICATOR',
        enable_diplay_log              TYPE string VALUE 'ENABLE_DIPLAY_LOG',
        fiscal_year_id                 TYPE string VALUE 'FISCAL_YEAR_ID',
        fixed_asset_class              TYPE string VALUE 'FIXED_ASSET_CLASS',
        BEGIN OF fixed_asset_key,
          BEGIN OF company_uuid,
            content                        TYPE string VALUE 'FIXED_ASSET_KEY-COMPANY_UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'FIXED_ASSET_KEY-COMPANY_UUID-SCHEME_ID',
          END OF company_uuid,
          BEGIN OF id,
            content                        TYPE string VALUE 'FIXED_ASSET_KEY-ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'FIXED_ASSET_KEY-ID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'FIXED_ASSET_KEY-ID-SCHEME_ID',
          END OF id,
          BEGIN OF master_fixed_asset_id,
            content                        TYPE string VALUE 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'FIXED_ASSET_KEY-MASTER_FIXED_ASSET_ID-SCHEME_ID',
          END OF master_fixed_asset_id,
        END OF fixed_asset_key,
        fxasr_type_code                TYPE string VALUE 'FXASR_TYPE_CODE',
        house_bank_id                  TYPE string VALUE 'HOUSE_BANK_ID',
        BEGIN OF id,
          content                        TYPE string VALUE 'ID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'ID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'ID-SCHEME_ID',
        END OF id,
        is_period_end_close_triggered  TYPE string VALUE 'IS_PERIOD_END_CLOSE_TRIGGERED',
        BEGIN OF key,
          cost_object_id                 TYPE string VALUE 'KEY-COST_OBJECT_ID',
          cost_object_type_code          TYPE string VALUE 'KEY-COST_OBJECT_TYPE_CODE',
        END OF key,
        life_cycle_status              TYPE string VALUE 'LIFE_CYCLE_STATUS',
        BEGIN OF log_section_uuid,
          content                        TYPE string VALUE 'LOG_SECTION_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'LOG_SECTION_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'LOG_SECTION_UUID-SCHEME_ID',
        END OF log_section_uuid,
        mdro_type_code                 TYPE string VALUE 'MDRO_TYPE_CODE',
        multi_customer_proj_indicator  TYPE string VALUE 'MULTI_CUSTOMER_PROJ_INDICATOR',
        ovh_assess_rule_id             TYPE string VALUE 'OVH_ASSESS_RULE_ID',
        party_role_category_code       TYPE string VALUE 'PARTY_ROLE_CATEGORY_CODE',
        permanent_establishment_id     TYPE string VALUE 'PERMANENT_ESTABLISHMENT_ID',
        BEGIN OF processing_status,
          processing_status_code         TYPE string VALUE 'PROCESSING_STATUS-PROCESSING_STATUS_CODE',
        END OF processing_status,
        BEGIN OF production_lot_formatted_id,
          formatted_id                   TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PRODUCTION_LOT_FORMATTED_ID-UUID-SCHEME_ID',
          END OF uuid,
        END OF production_lot_formatted_id,
        product_type_code              TYPE string VALUE 'PRODUCT_TYPE_CODE',
        projection_bo_name             TYPE string VALUE 'PROJECTION_BO_NAME',
        BEGIN OF project_id,
          content                        TYPE string VALUE 'PROJECT_ID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'PROJECT_ID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'PROJECT_ID-SCHEME_ID',
        END OF project_id,
        project_task_id                TYPE string VALUE 'PROJECT_TASK_ID',
        BEGIN OF purchase_doc_id,
          formatted_id                   TYPE string VALUE 'PURCHASE_DOC_ID-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC_ID-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC_ID-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC_ID-UUID-SCHEME_ID',
          END OF uuid,
        END OF purchase_doc_id,
        BEGIN OF purchase_doc_id_upb,
          formatted_id                   TYPE string VALUE 'PURCHASE_DOC_ID_UPB-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'PURCHASE_DOC_ID_UPB-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'PURCHASE_DOC_ID_UPB-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'PURCHASE_DOC_ID_UPB-UUID-SCHEME_ID',
          END OF uuid,
        END OF purchase_doc_id_upb,
        BEGIN OF purchase_doc_type,
          content                        TYPE string VALUE 'PURCHASE_DOC_TYPE-CONTENT',
          list_id                        TYPE string VALUE 'PURCHASE_DOC_TYPE-LIST_ID',
        END OF purchase_doc_type,
        BEGIN OF rac_id,
          formatted_id                   TYPE string VALUE 'RAC_ID-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'RAC_ID-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'RAC_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'RAC_ID-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'RAC_ID-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'RAC_ID-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'RAC_ID-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'RAC_ID-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'RAC_ID-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'RAC_ID-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'RAC_ID-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'RAC_ID-UUID-SCHEME_ID',
          END OF uuid,
        END OF rac_id,
        BEGIN OF sales_document_id,
          formatted_id                   TYPE string VALUE 'SALES_DOCUMENT_ID-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'SALES_DOCUMENT_ID-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'SALES_DOCUMENT_ID-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SALES_DOCUMENT_ID-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'SALES_DOCUMENT_ID-UUID-SCHEME_ID',
          END OF uuid,
        END OF sales_document_id,
        BEGIN OF sales_document_type,
          content                        TYPE string VALUE 'SALES_DOCUMENT_TYPE-CONTENT',
          list_id                        TYPE string VALUE 'SALES_DOCUMENT_TYPE-LIST_ID',
        END OF sales_document_type,
        sales_obj_sel_code             TYPE string VALUE 'SALES_OBJ_SEL_CODE',
        sales_organisation_id          TYPE string VALUE 'SALES_ORGANISATION_ID',
        BEGIN OF set_of_books_id,
          content                        TYPE string VALUE 'SET_OF_BOOKS_ID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'SET_OF_BOOKS_ID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'SET_OF_BOOKS_ID-SCHEME_ID',
        END OF set_of_books_id,
        BEGIN OF sob_asset_valuation_view_key,
          BEGIN OF set_of_books_id,
            content                        TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SET_OF_BOOKS_ID-SCHEME_ID',
          END OF set_of_books_id,
          BEGIN OF sob_asset_valuation_view_id,
            content                        TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'SOB_ASSET_VALUATION_VIEW_KEY-SOB_ASSET_VALUATION_VIEW_ID-SCHEME_ID',
          END OF sob_asset_valuation_view_id,
        END OF sob_asset_valuation_view_key,
        test_run_indicator             TYPE string VALUE 'TEST_RUN_INDICATOR',
        third_party_deal_indicator     TYPE string VALUE 'THIRD_PARTY_DEAL_INDICATOR',
      END OF root,
      BEGIN OF sales_organisation,
        BEGIN OF name,
          content                        TYPE string VALUE 'NAME-CONTENT',
          language_code                  TYPE string VALUE 'NAME-LANGUAGE_CODE',
        END OF name,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF sales_organisation,
      BEGIN OF sal_ser_doc,
        BEGIN OF cust_ret_name,
          content                        TYPE string VALUE 'CUST_RET_NAME-CONTENT',
          language_code                  TYPE string VALUE 'CUST_RET_NAME-LANGUAGE_CODE',
        END OF cust_ret_name,
        BEGIN OF sal_ord_name,
          content                        TYPE string VALUE 'SAL_ORD_NAME-CONTENT',
          language_code                  TYPE string VALUE 'SAL_ORD_NAME-LANGUAGE_CODE',
        END OF sal_ord_name,
        BEGIN OF sal_ser_doc,
          formatted_id                   TYPE string VALUE 'SAL_SER_DOC-FORMATTED_ID',
          BEGIN OF object_id,
            content                        TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_ID',
            scheme_agency_scheme_agency_id TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_AGENCY_ID',
            scheme_agency_scheme_id        TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-SCHEME_AGENCY_SCHEME_ID',
            scheme_id                      TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-SCHEME_ID',
            scheme_version_id              TYPE string VALUE 'SAL_SER_DOC-OBJECT_ID-SCHEME_VERSION_ID',
          END OF object_id,
          BEGIN OF object_node_type_code,
            content                        TYPE string VALUE 'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'SAL_SER_DOC-OBJECT_NODE_TYPE_CODE-LIST_ID',
          END OF object_node_type_code,
          BEGIN OF object_type_code,
            content                        TYPE string VALUE 'SAL_SER_DOC-OBJECT_TYPE_CODE-CONTENT',
            list_id                        TYPE string VALUE 'SAL_SER_DOC-OBJECT_TYPE_CODE-LIST_ID',
          END OF object_type_code,
          BEGIN OF uuid,
            content                        TYPE string VALUE 'SAL_SER_DOC-UUID-CONTENT',
            scheme_agency_id               TYPE string VALUE 'SAL_SER_DOC-UUID-SCHEME_AGENCY_ID',
            scheme_id                      TYPE string VALUE 'SAL_SER_DOC-UUID-SCHEME_ID',
          END OF uuid,
        END OF sal_ser_doc,
        BEGIN OF ser_conf_name,
          content                        TYPE string VALUE 'SER_CONF_NAME-CONTENT',
          language_code                  TYPE string VALUE 'SER_CONF_NAME-LANGUAGE_CODE',
        END OF ser_conf_name,
        BEGIN OF ser_ord_name,
          content                        TYPE string VALUE 'SER_ORD_NAME-CONTENT',
          language_code                  TYPE string VALUE 'SER_ORD_NAME-LANGUAGE_CODE',
        END OF ser_ord_name,
      END OF sal_ser_doc,
      BEGIN OF sel_by_production_lot,
        inclusion_exclusion_code       TYPE string VALUE 'INCLUSION_EXCLUSION_CODE',
        interval_boundary_type_code    TYPE string VALUE 'INTERVAL_BOUNDARY_TYPE_CODE',
        lowb_prod_lot_formatted_id     TYPE string VALUE 'LOWB_PROD_LOT_FORMATTED_ID',
        BEGIN OF lowb_prod_lot_uuid,
          content                        TYPE string VALUE 'LOWB_PROD_LOT_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'LOWB_PROD_LOT_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'LOWB_PROD_LOT_UUID-SCHEME_ID',
        END OF lowb_prod_lot_uuid,
        upb_prod_lot_formatted_id      TYPE string VALUE 'UPB_PROD_LOT_FORMATTED_ID',
        BEGIN OF upb_prod_lot_uuid,
          content                        TYPE string VALUE 'UPB_PROD_LOT_UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UPB_PROD_LOT_UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UPB_PROD_LOT_UUID-SCHEME_ID',
        END OF upb_prod_lot_uuid,
      END OF sel_by_production_lot,
      BEGIN OF set_of_books,
        BEGIN OF description,
          content                        TYPE string VALUE 'DESCRIPTION-CONTENT',
          language_code                  TYPE string VALUE 'DESCRIPTION-LANGUAGE_CODE',
        END OF description,
        BEGIN OF uuid,
          content                        TYPE string VALUE 'UUID-CONTENT',
          scheme_agency_id               TYPE string VALUE 'UUID-SCHEME_AGENCY_ID',
          scheme_id                      TYPE string VALUE 'UUID-SCHEME_ID',
        END OF uuid,
      END OF set_of_books,
    END OF co_attr .
  constants:
    BEGIN OF CO_ACTION_P_ATTR,
      BEGIN OF root,
        BEGIN OF compound_schedule,
          planned_date_time              TYPE string VALUE 'PLANNED_DATE_TIME',
        END OF compound_schedule,
        BEGIN OF create,
          ap_or_ar                       TYPE string VALUE 'AP_OR_AR',
          cancellation_run_indicator     TYPE string VALUE 'CANCELLATION_RUN_INDICATOR',
          mdro_type_code                 TYPE string VALUE 'MDRO_TYPE_CODE',
          test_run_indicator             TYPE string VALUE 'TEST_RUN_INDICATOR',
        END OF create,
      END OF root,
    END OF CO_ACTION_P_ATTR .
endinterface.